#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/CustomMaster.cshtml")]
    public partial class _Views_Shared_Layouts_CustomMaster_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel>
    {
        public _Views_Shared_Layouts_CustomMaster_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n\r\n");

WriteLiteral("\r\n");

DefineSection("CmsHeadScripts", () => {

WriteLiteral("\r\n    <head>\r\n        \r\n\r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n        <meta");

WriteLiteral(" http-equiv=\"last-modified\"");

WriteLiteral(" content=\"2015-09-29@12:22:00 GMT\"");

WriteLiteral(" />\r\n        <title>NYC English</title>\r\n\r\n        <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(@" content="" Using high definition videos, music, and animations, NYC English engages you with authentic English language communication. You, the learner, can watch and hear your mentors and practice simple communicative tasks with our voice recognition tool, apply grammar rules to conversations, and improve your speaking skills with our key words. Each NYCE lesson models teaching ideas for educators, simple classroom activities, and role plays. With 90 themes available, you are able to learn and practice a variety of English concepts in a fun and engaging way!""");

WriteLiteral(">\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/main.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/modal.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/slick/slick.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/Expand.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/responsive.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/responsive_1.css?v=1\"");

WriteLiteral(" />\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/css/swiper.min.css?v=1\"");

WriteLiteral(">\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
            var contryIconWidth;
            if (document.images)
                (new Image()).src = ""/images/logo_small_1.png"";
            (new Image()).src = ""/images/banner_img.jpg"";
            (new Image()).src = ""/images/user_1.png"";
            (new Image()).src = ""/images/user_2.png"";
            (new Image()).src = ""/images/user_3.png"";

        </script>
        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1919), Tuple.Create("\"", 1950)
, Tuple.Create(Tuple.Create("", 1925), Tuple.Create<System.Object, System.Int32>(Href("~/js/jquery-1.11.1.js?v=1")
, 1925), false)
);

WriteLiteral("></script>\r\n        ");

WriteLiteral("\r\n        ");

WriteLiteral("\r\n        ");

WriteLiteral("\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n           \r\n            function resumeSlider() {\r\n                if ($(\'#ba" +
"nner-mobile\').css(\'display\') == \'block\') {\r\n                    $(\'#wrapper\').cs" +
"s(\'height\', \'40px\');\r\n                    $(\'#wrapper\').css(\'bottom\', \'5px\');\r\n " +
"                   $(\'.bannerTextContainer\').css(\'height\', \'120px\');\r\n          " +
"          //                $(\'#heading .InnerText\').css(\'font-size\', \'15px\');\r\n" +
"                    $(\'#carousel div\').css(\'width\', \'150px\');\r\n                 " +
"   contryIconWidth = $(\'#carousel .contryIcon\').width();\r\n                } else" +
" {\r\n                    $(\'.caroufredsel_wrapper\').css(\'top\', \'14px\');\r\n        " +
"            $(\'.caroufredsel_wrapper\').css(\'width\', \'100%\').css(\'width\', \'+=500p" +
"x\');\r\n                    $(\'.caroufredsel_wrapper\').css(\'height\', \'100%\');\r\n   " +
"                 $(\'.caroufredsel_wrapper\').css(\'top\', \'0px\');\r\n                " +
"    $(\'#carousel2 .contryIcon\').css(\'font-size\', \'13px\');\r\n                    c" +
"ontryIconWidth = $(\'#carousel2 .contryIcon\').width();\r\n                }\r\n\r\n    " +
"        }\r\n\r\n            //$(function () {\r\n            //    var $c = $(\'#carou" +
"sel\');\r\n            //    $w = $(window);\r\n            //    $c.carouFredSel({\r\n" +
"            //        align: false,\r\n            //        items: 15,\r\n         " +
"   //        scroll: {\r\n            //            items: 1,\r\n            //     " +
"       responsive: true,\r\n            //            duration: 2500,\r\n           " +
" //            timeoutDuration: 0,\r\n            //            easing: \'linear\',\r" +
"\n            //            pauseOnHover: \'immediate\'\r\n            //        }\r\n " +
"           ////    });\r\n                $w.bind(\'resize.example\', function () {\r" +
"\n                    $c.width(\'100%\');\r\n                    $c.parent().width(\'1" +
"00%\');\r\n                    $c.height(\'100%\');\r\n                    $c.parent()." +
"width(\'100%\');\r\n                    $(\'.caroufredsel_wrapper\').width($(\'#wrapper" +
"\').width() + 500);\r\n                    $(\'.caroufredsel_wrapper\').height(\'100%\'" +
");\r\n                }).trigger(\'resize.example\');\r\n\r\n                $c.width(\'1" +
"00%\');\r\n                $c.parent().width(\'100%\');\r\n                $c.height(\'1" +
"00%\');\r\n                $c.parent().width(\'100%\');\r\n                $(\'.caroufre" +
"dsel_wrapper\').width($(\'#wrapper\').width() + 500);\r\n                $(\'.caroufre" +
"dsel_wrapper\').height(\'100%\');\r\n                $(\'#wrapper\').css(\'height\', \'40p" +
"x\');\r\n                $(\'#wrapper\').css(\'bottom\', \'5px\');\r\n                $(\'.b" +
"annerTextContainer\').css(\'height\', \'120px\');\r\n                $(\'#carousel .cont" +
"ryIcon\').css(\'font-size\', \'15px\');\r\n                $(\'#carousel div\').css(\'widt" +
"h\', \'130px\');\r\n                contryIconWidth = $(\'#carousel .contryIcon\').widt" +
"h();\r\n          //  });\r\n            $(function () {\r\n                var $ca = " +
"$(\'#carousel2\');\r\n                $wa = $(window);\r\n                $ca.carouFre" +
"dSel({\r\n                    align: false,\r\n                    items: 12,\r\n     " +
"               scroll: {\r\n                        items: 1,\r\n                   " +
"     duration: 2500,\r\n                        timeoutDuration: 0,\r\n             " +
"           easing: \'linear\',\r\n                        pauseOnHover: \'immediate\'\r" +
"\n                    }\r\n                });\r\n                $wa.bind(\'resize.ex" +
"ample\', function () {\r\n                    $ca.width(\'100%\');\r\n                 " +
"   $ca.parent().width(\'100%\');\r\n                    $ca.height(\'100%\');\r\n       " +
"             $ca.parent().width(\'100%\');\r\n                    $(\'.caroufredsel_w" +
"rapper\').css(\'top\', \'14px\');\r\n                    $(\'.caroufredsel_wrapper\').css" +
"(\'width\', \'100%\').css(\'width\', \'+=500px\');\r\n                    $(\'.caroufredsel" +
"_wrapper\').css(\'height\', \'100%\');\r\n                    $(\'.caroufredsel_wrapper\'" +
").css(\'top\', \'0px\');\r\n                    $(\'#carousel2 .contryIcon\').css(\'font-" +
"size\', \'13px\');\r\n                }).trigger(\'resize.example\');\r\n                " +
"contryIconWidth = $(\'#carousel2 .contryIcon\').width();\r\n\r\n            });\r\n     " +
"       $(document).ready(function () {\r\n                $(\'#showHideMenu\').click" +
"(function () {\r\n                    alert(\"showHideMenu\");\r\n                });\r" +
"\n                var vid = document.getElementById(\'vdo\');\r\n                if (" +
"$(\'#banner-mobile\').css(\'display\') == \'block\')\r\n                    contryIconWi" +
"dth = $(\'#carousel .contryIcon\').width();\r\n                else\r\n               " +
"     contryIconWidth = $(\'#carousel2 .contryIcon\').width();\r\n\r\n                $" +
"(\'#btnVideo\').click(function () {\r\n                    document.getElementById(\'" +
"vdo\').play();\r\n                    $(\'#modalVideo\').css(\'display\', \'block\');\r\n  " +
"              });\r\n                $(\'#getStarted\').click(function () {\r\n       " +
"             $(\'#modalGetInfo\').css(\'display\', \'block\');\r\n                });\r\n\r" +
"\n                $(\'.LoginContainer a.FreeTrial\').on(\"click\", function () {\r\n   " +
"                 window.open(\"https://www.nycenglish.net/register.html\", \"_blank" +
"\");\r\n                });\r\n\r\n                $(\'.modalGetInfo-body .item:nth-of-t" +
"ype(1)\').click(function () {\r\n                    window.open(\"http://placementt" +
"est.nycenglish.net/\", \"_blank\");\r\n                });\r\n\r\n                $(\'.mod" +
"alGetInfo-body .item:nth-of-type(2)\').click(function () {\r\n                    w" +
"indow.open(\"https://www.nycenglish.net/\", \"_blank\");\r\n                });\r\n\r\n   " +
"             $(\'.modalGetInfo-body .item:nth-of-type(3)\').click(function () {\r\n " +
"                   window.open(\"http://lms.nyceonline.nyc/\", \"_blank\");\r\n       " +
"         });\r\n\r\n                $(\'.cross\').click(function () {\r\n               " +
"     document.getElementById(\'vdo\').pause();\r\n                    document.getEl" +
"ementById(\'vdo\').currentTime = 0;\r\n                    $(\'#modalVideo\').css(\'dis" +
"play\', \'none\');\r\n                });\r\n                $(\'.modalGetInfo-header .c" +
"ross\').click(function () {\r\n                    $(\'#modalGetInfo\').css(\'display\'" +
", \'none\');\r\n                });\r\n\r\n                //$(\'#modalVideo\').css(\'displ" +
"ay\', \'block\');\r\n\r\n                $(\"#vdo\").bind(\'timeupdate\', onVideoTimeupdate" +
");\r\n\r\n                function onVideoTimeupdate() {\r\n                    try {\r" +
"\n                        if (this.duration > 0) {\r\n                            i" +
"f (this.currentTime >= this.duration) {\r\n                                $(\'#mod" +
"alVideo\').css(\'display\', \'none\');\r\n                            }\r\n              " +
"          }\r\n                    } catch (e) {\r\n                        //alert(" +
"e);\r\n                    }\r\n                }\r\n\r\n            });\r\n            $(" +
"window).resize(function () {\r\n                $(\'#carousel2\').trigger(\'mouseout\'" +
");\r\n                $(\'#carousel\').trigger(\'mouseout\');\r\n                resumeS" +
"lider();\r\n            });\r\n\r\n        </script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/js/page.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/js/mail.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/js/features.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" src=\"/js/swiper.min.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/js/jquery.touchswipe.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" src=\"/js/swipeScroll.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" src=\"/js/app.js?v=1\"");

WriteLiteral("></script>\r\n        <script");

WriteLiteral(" src=\"/js/modernizr.js?v=1\"");

WriteLiteral("></script>\r\n    </head>\r\n");

});

WriteLiteral("\r\n\r\n\r\n\r\n\r\n");

            
            #line 208 "..\..\Views\Shared\Layouts\CustomMaster.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n<body");

WriteLiteral(" style=\"min-height: inherit; min-width: 320px;\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n\r\n    </script>\r\n    <div");

WriteLiteral(" id=\"mainContainer\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"LoginContainer\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"videobtn\"");

WriteLiteral(" id=\"btnVideo\"");

WriteLiteral(@"></a>
            <!--
                        <a class=""LoginCourse"" href=""http://www.nycenglish.net/"" target=""_blank""></a>
                        <a class=""PlacementTest"" href=""http://placementtest.nycenglish.net/"" target=""_blank""></a>
                        <a class=""Logindashboard"" href=""http://lms.nyceonline.nyc/"" target=""_blank""></a>
            -->
            <a");

WriteLiteral(" class=\"Logindashboard\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" id=\"getStarted\"");

WriteLiteral("></a>\r\n            <a");

WriteLiteral(" class=\"FreeTrial\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" id=\"getTrial\"");

WriteLiteral("></a>\r\n        </div>\r\n        ");

WriteLiteral("\r\n        <!--Banner Mobile -->\r\n        <div");

WriteLiteral(" class=\"mobile-header nav-down\"");

WriteLiteral(" id=\"mobile_header\"");

WriteLiteral(" style=\"z-index: 777777\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"showHideMenu\"");

WriteLiteral(" class=\"show-hide-menu s-buttonNew\"");

WriteLiteral(" data-sidebar-button=\"\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/images/icon_menu.png\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"mobile-logo\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"/images/banner_logo.png\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" data-sidebar-overlay=\"\"");

WriteLiteral(" class=\"overlay\"");

WriteLiteral(" style=\"display: block; opacity: 0.5;\"");

WriteLiteral(">\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"aside\"");

WriteLiteral(" data-sidebar=\"\"");

WriteLiteral(" style=\"z-index: 888888\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sidebar-top\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"width: 55px;\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"/images/logo_small.png\"");

WriteLiteral(" class=\"logo-mobile\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"overflow-x: hidden; overflow-y: hidden; clear: both; height: 70%\"");

WriteLiteral(" id=\"mobile-menu\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" id=\"nav_menu\"");

WriteLiteral(" class=\"nav-menu\"");

WriteLiteral(">\r\n                    <li>\r\n                        <a");

WriteLiteral(" name=\"#banner-mobile\"");

WriteLiteral(" id=\"home-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                            Home\r\n                        </a>\r\n              " +
"      </li>\r\n                    <li>\r\n                        <a");

WriteLiteral(" name=\"#feature\"");

WriteLiteral(" id=\"feature-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(">Features</a>\r\n                    </li>\r\n                    <li>\r\n             " +
"           <a");

WriteLiteral(" name=\"#download-mobile\"");

WriteLiteral(" id=\"download-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(">Download</a>\r\n                    </li>\r\n                    <li><a");

WriteLiteral(" name=\"#faq\"");

WriteLiteral(" id=\"faq-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(">FAQ</a> </li>\r\n                    <li>\r\n                        <a");

WriteLiteral(" name=\"#aboutUs\"");

WriteLiteral(" id=\"about-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(">About us</a>\r\n                    </li>\r\n                    <li>\r\n             " +
"           <a");

WriteLiteral(" name=\"#contectUs\"");

WriteLiteral(" id=\"contact-link\"");

WriteLiteral(" onclick=\"makeSelected(this);\"");

WriteLiteral(">Contact us</a>\r\n                    </li>\r\n                </ul>\r\n            </" +
"div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" id=\"banner-mobile\"");

WriteLiteral(">\r\n            <!--<img alt=\"\" src=\"/images/mobile_banner.jpg\" />-->\r\n           " +
" <div");

WriteLiteral(" id=\"user_img_mobile\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_1\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_2\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_3\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_4\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_5\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_6\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_7\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_8\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_9\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_10\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"user_img_mobile\"");

WriteLiteral(" id=\"user_m_11\"");

WriteLiteral(">\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"large-4 medium-4 small-12 column bannerTextContainer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"bannerBox-mobile\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"heading\"");

WriteLiteral(" style=\"line-height:75px;\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"InnerText\"");

WriteLiteral("></span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" id=\"countries-mobile\"");

WriteLiteral(" style=\"width: 100%; height: 40%; color: #262626;\r\n                            xl" +
"ine-height: 30px;\"");

WriteLiteral(">\r\n                            <!--         MOBILE CAROUSEL           -->\r\n      " +
"                      <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" id=\"carousel\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"vietnam_Img\"");

WriteLiteral(" country=\"vietnam\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_vietnam.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Vietnam</span>\r\n                                    </div>\r\n                    " +
"                <div");

WriteLiteral(" id=\"china_Img\"");

WriteLiteral(" country=\"china\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_china.png\"");

WriteLiteral(" />\r\n                                        <span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">China</span>\r\n                                    </div>\r\n\r\n                    " +
"                <div");

WriteLiteral(" id=\"columbia_Img\"");

WriteLiteral(" country=\"columbia\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_columbia.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Colombia</span>\r\n                                    </div>\r\n                   " +
"                 <div");

WriteLiteral(" id=\"cyprus_Img\"");

WriteLiteral(" country=\"cyprus\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_cyprus.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Cyprus</span>\r\n                                    </div>\r\n                     " +
"               <div");

WriteLiteral(" id=\"ecuador_Img\"");

WriteLiteral(" country=\"ecuador\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_ecuador.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Ecuador</span>\r\n                                    </div>\r\n                    " +
"                <div");

WriteLiteral(" id=\"greece_Img\"");

WriteLiteral(" country=\"greece\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_greece.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Greece</span>\r\n                                    </div>\r\n                     " +
"               <div");

WriteLiteral(" id=\"hongkong_Img\"");

WriteLiteral(" country=\"hongkong\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_hongkong.png\"");

WriteLiteral(" />\r\n                                        <span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Hong Kong</span>\r\n                                    </div>\r\n                  " +
"                  <div");

WriteLiteral(" id=\"indonasia_Img\"");

WriteLiteral(" country=\"indonasia\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_indonesia.png\"");

WriteLiteral(" />\r\n                                        <span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Indonesia</span>\r\n                                    </div>\r\n                  " +
"                  <div");

WriteLiteral(" id=\"india_Img\"");

WriteLiteral(" country=\"india\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_india.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">India</span>\r\n                                    </div>\r\n                      " +
"              <div");

WriteLiteral(" id=\"japan_Img\"");

WriteLiteral(" country=\"japan\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_japan.png\"");

WriteLiteral(" />\r\n                                        <span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Japan</span>\r\n                                    </div>\r\n                      " +
"              <div");

WriteLiteral(" id=\"korea_Img\"");

WriteLiteral(" country=\"korea\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_korea.png\"");

WriteLiteral(" />\r\n                                        <span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Korea</span>\r\n                                    </div>\r\n                      " +
"              <div");

WriteLiteral(" id=\"malaysia_Img\"");

WriteLiteral(" country=\"malaysia\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_malaysia.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Malaysia</span>\r\n                                    </div>\r\n                   " +
"                 <div");

WriteLiteral(" id=\"mexico_Img\"");

WriteLiteral(" country=\"mexico\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_mexico.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Mexico</span>\r\n                                    </div>\r\n                     " +
"               <div");

WriteLiteral(" id=\"myanmar_Img\"");

WriteLiteral(" country=\"myanmar\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_myanmar.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Myanmar</span>\r\n                                    </div>\r\n                    " +
"                <div");

WriteLiteral(" id=\"philippines_Img\"");

WriteLiteral(" country=\"philippines\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_philippines.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Philippines</span>\r\n                                    </div>\r\n                " +
"                    <div");

WriteLiteral(" id=\"poland_Img\"");

WriteLiteral(" country=\"poland\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_poland.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Poland</span>\r\n                                    </div>\r\n                     " +
"               <div");

WriteLiteral(" id=\"singapore_Img\"");

WriteLiteral(" country=\"singapore\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_singapore.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Singapore</span>\r\n                                    </div>\r\n                  " +
"                  <div");

WriteLiteral(" id=\"srilanka_Img\"");

WriteLiteral(" country=\"srilanka\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_srilanka.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Sri Lanka</span>\r\n                                    </div>\r\n                  " +
"                  <div");

WriteLiteral(" id=\"thailand_Img\"");

WriteLiteral(" country=\"thailand\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_thailand.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(">Thailand</span>\r\n                                    </div>\r\n                   " +
"                 <div");

WriteLiteral(" id=\"usa_Img\"");

WriteLiteral(" country=\"usa\"");

WriteLiteral(" class=\"contryIcon\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/flag_usa.png\"");

WriteLiteral(" /><span");

WriteLiteral(" style=\"margin-left:10px;color:white;font-size:15px;font-family:Arial;font-weight" +
":bold;\"");

WriteLiteral(@">Usa</span>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- -->
        <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" id=\"banner\"");

WriteLiteral(" style=\"position: relative;overflow:hidden;\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/banner_img.jpg\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"position: absolute; top: 0; height: 100%; padding-top: 12px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"userImage\"");

WriteLiteral(" class=\"large-4 medium-4 small-12 column\"");

WriteLiteral(" style=\"position: relative\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_1\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_2\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_3\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_4\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_5\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_6\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_7\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_8\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_9\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_10\"");

WriteLiteral(">\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"user_img\"");

WriteLiteral(" id=\"user_11\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n                <!--------" +
"------->\r\n                <div class=\"large-4 medium-7 small-12 column textConta" +
"iner\" style=\"width:96%;position:absolute;top:44%;left:2%\">\r\n                    " +
"<div id=\"heading\" class=\"heading\" style=\"position:absolute; bottom: 76%;left:35%" +
";width:22%;color:black;\">\r\n                        <span class=\"InnerText\"></spa" +
"n>\r\n                    </div>\r\n                    <div id=\"bannerBox\" style=\"\"" +
">\r\n                        <div id=\"countries-desktop\" style=\"width: 100%; font-" +
"size: 14px; color: #262626;\">\r\n                            <div id=\"wrapper2\">\r\n" +
"                                <div id=\"carousel2\">\r\n                          " +
"          <div id=\"vietnam_Img\" country=\"vietnam\" class=\"contryIcon\">\r\n         " +
"                               <img alt=\"\" src=\"/images/flag_vietnam.png\" class=" +
"\"IconWidth\" />\r\n                                        <span style=\"margin-left" +
":10px;color:white;font-size:18px;font-family:Arial;font-weight:bold;\">Vietnam</s" +
"pan>\r\n                                    </div>\r\n\r\n                            " +
"        <div id=\"china_Img\" country=\"china\" class=\"contryIcon\">\r\n               " +
"                         <img alt=\"\" src=\"/images/flag_china.png\" class=\"IconWid" +
"th\" />\r\n                                        <span style=\"margin-left:10px;co" +
"lor:white;font-size:18px;font-family:Arial;font-weight:bold;\">China</span>\r\n    " +
"                                </div>\r\n                                    <div" +
" id=\"columbia_Img\" country=\"columbia\" class=\"contryIcon\">\r\n                     " +
"                   <img alt=\"\" src=\"/images/flag_columbia.png\" class=\"IconWidth\"" +
" />\r\n                                        <span style=\"margin-left:10px;color" +
":white;font-size:18px;font-family:Arial;font-weight:bold;\">Colombia</span>\r\n    " +
"                                </div>\r\n                                    <div" +
" id=\"cyprus_Img\" country=\"cyprus\" class=\"contryIcon\">\r\n                         " +
"               <img alt=\"\" src=\"/images/flag_cyprus.png\" class=\"IconWidth\" /><sp" +
"an style=\"margin-left:10px;color:white;font-size:18px;font-family:Arial;font-wei" +
"ght:bold;\">Cyprus</span>\r\n                                    </div>\r\n          " +
"                          <div id=\"ecuador_Img\" country=\"ecuador\" class=\"contryI" +
"con\">\r\n                                        <img alt=\"\" src=\"/images/flag_ecu" +
"ador.png\" class=\"IconWidth\" />\r\n                                        <span st" +
"yle=\"margin-left:10px;color:white;font-size:18px;font-family:Arial;font-weight:b" +
"old;\">Ecuador</span>\r\n                                    </div>\r\n              " +
"                      <div id=\"greece_Img\" country=\"greece\" class=\"contryIcon\">\r" +
"\n                                        <img alt=\"\" src=\"/images/flag_greece.pn" +
"g\" class=\"IconWidth\" /><span style=\"margin-left:10px;color:white;font-size:18px;" +
"font-family:Arial;font-weight:bold;\">Greece</span>\r\n                            " +
"        </div>\r\n                                    <div id=\"hongkong_Img\" count" +
"ry=\"hongkong\" class=\"contryIcon\">\r\n                                        <img " +
"alt=\"\" src=\"/images/flag_hongkong.png\" class=\"IconWidth\" />\r\n                   " +
"                     <span style=\"margin-left:10px;color:white;font-size:18px;fo" +
"nt-family:Arial;font-weight:bold;\">Hong Kong</span>\r\n                           " +
"         </div>\r\n                                    <div id=\"indonasia_Img\" cou" +
"ntry=\"indonasia\" class=\"contryIcon\">\r\n                                        <i" +
"mg alt=\"\" src=\"/images/flag_indonesia.png\" class=\"IconWidth\" />\r\n               " +
"                         <span style=\"margin-left:10px;color:white;font-size:18p" +
"x;font-family:Arial;font-weight:bold;\">Indonesia</span>\r\n                       " +
"             </div>\r\n                                    <div id=\"india_Img\" cou" +
"ntry=\"india\" class=\"contryIcon\">\r\n                                        <img a" +
"lt=\"\" src=\"/images/flag_india.png\" class=\"IconWidth\" /><span style=\"margin-left:" +
"10px;color:white;font-size:18px;font-family:Arial;font-weight:bold;\">India</span" +
">\r\n                                    </div>\r\n                                 " +
"   <div id=\"japan_Img\" country=\"japan\" class=\"contryIcon\">\r\n                    " +
"                    <img alt=\"\" src=\"/images/flag_japan.png\" class=\"IconWidth\" /" +
">\r\n                                        <span style=\"margin-left:10px;color:w" +
"hite;font-size:18px;font-family:Arial;font-weight:bold;\">Japan</span>\r\n         " +
"                           </div>\r\n                                    <div id=\"" +
"korea_Img\" country=\"korea\" class=\"contryIcon\">\r\n                                " +
"        <img alt=\"\" src=\"/images/flag_korea.png\" class=\"IconWidth\" />\r\n         " +
"                               <span style=\"margin-left:10px;color:white;font-si" +
"ze:18px;font-family:Arial;font-weight:bold;\">Korea</span>\r\n                     " +
"               </div>\r\n                                    <div id=\"malaysia_Img" +
"\" country=\"malaysia\" class=\"contryIcon\">\r\n                                      " +
"  <img alt=\"\" src=\"/images/flag_malaysia.png\" class=\"IconWidth\" />\r\n            " +
"                            <span style=\"margin-left:10px;color:white;font-size:" +
"18px;font-family:Arial;font-weight:bold;\">Malaysia</span>\r\n                     " +
"               </div>\r\n                                    <div id=\"mexico_Img\" " +
"country=\"mexico\" class=\"contryIcon\">\r\n                                        <i" +
"mg alt=\"\" src=\"/images/flag_mexico.png\" class=\"IconWidth\" />\r\n                  " +
"                      <span style=\"margin-left:10px;color:white;font-size:18px;f" +
"ont-family:Arial;font-weight:bold;\">Mexico</span>\r\n                             " +
"       </div>\r\n                                    <div id=\"myanmar_Img\" country" +
"=\"myanmar\" class=\"contryIcon\">\r\n                                        <img alt" +
"=\"\" src=\"/images/flag_myanmar.png\" class=\"IconWidth\" />\r\n                       " +
"                 <span style=\"margin-left:10px;color:white;font-size:18px;font-f" +
"amily:Arial;font-weight:bold;\">Myanmar</span>\r\n                                 " +
"   </div>\r\n                                    <div id=\"philippines_Img\" country" +
"=\"philippines\" class=\"contryIcon\">\r\n                                        <img" +
" alt=\"\" src=\"/images/flag_philippines.png\" class=\"IconWidth\" />\r\n               " +
"                         <span style=\"margin-left:10px;color:white;font-size:18p" +
"x;font-family:Arial;font-weight:bold;\">Philippines</span>\r\n                     " +
"               </div>\r\n                                    <div id=\"poland_Img\" " +
"country=\"poland\" class=\"contryIcon\">\r\n                                        <i" +
"mg alt=\"\" src=\"/images/flag_poland.png\" class=\"IconWidth\" />\r\n                  " +
"                      <span style=\"margin-left:10px;color:white;font-size:18px;f" +
"ont-family:Arial;font-weight:bold;\">Poland</span>\r\n                             " +
"       </div>\r\n                                    <div id=\"singapore_Img\" count" +
"ry=\"singapore\" class=\"contryIcon\">\r\n                                        <img" +
" alt=\"\" src=\"/images/flag_singapore.png\" class=\"IconWidth\" />\r\n                 " +
"                       <span style=\"margin-left:10px;color:white;font-size:18px;" +
"font-family:Arial;font-weight:bold;\">Singapore</span>\r\n                         " +
"           </div>\r\n                                    <div id=\"srilanka_Img\" co" +
"untry=\"srilanka\" class=\"contryIcon\">\r\n                                        <i" +
"mg alt=\"\" src=\"/images/flag_srilanka.png\" class=\"IconWidth\" />\r\n                " +
"                        <span style=\"margin-left:10px;color:white;font-size:18px" +
";font-family:Arial;font-weight:bold;\">Sri Lanka</span>\r\n                        " +
"            </div>\r\n                                    <div id=\"thailand_Img\" c" +
"ountry=\"thailand\" class=\"contryIcon\">\r\n                                        <" +
"img alt=\"\" src=\"/images/flag_thailand.png\" class=\"IconWidth\" />\r\n               " +
"                         <span style=\"margin-left:10px;color:white;font-size:18p" +
"x;font-family:Arial;font-weight:bold;\">Thailand</span>\r\n                        " +
"            </div>\r\n                                    <div id=\"usa_Img\" countr" +
"y=\"usa\" class=\"contryIcon\">\r\n                                        <img alt=\"\"" +
" src=\"/images/flag_usa.png\" class=\"IconWidth\" />\r\n                              " +
"          <span style=\"margin-left:10px;color:white;font-size:18px;font-family:A" +
"rial;font-weight:bold;\">USA</span>\r\n                                    </div>\r\n" +
"\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <!------------------------" +
"------------------------------------------>\r\n                    </div>\r\n       " +
"         </div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"logoImage\"");

WriteLiteral(" class=\"large-4 medium-4 small-12 column end\"");

WriteLiteral(" style=\"position:absolute;top:1%;left:63%;\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/banner_logo.png\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"navAnchor\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" style=\"width: 100%; background-color: white; z-index: 1000\"");

WriteLiteral(" id=\"sticky_navigation\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"width: 20%; height: 100px; float: left\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"logoMenu\"");

WriteLiteral(" style=\"display: none; width: 100%; height: 100%; padding: 30px\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" onclick=\"smoothScroll(\'banner\')\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/logo_small.png\"");

WriteLiteral(" />\r\n                </a>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"demo_container\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" id=\"top-menu\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" name=\"#feature\"");

WriteLiteral(" id=\"fLink\"");

WriteLiteral(" onclick=\"activeClass(this);\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/icon_features.png\"");

WriteLiteral(" id=\"featureLink\"");

WriteLiteral(" />\r\n                        <span>Features</span>\r\n                    </a>\r\n   " +
"             </li>\r\n                <li>\r\n                    <a");

WriteLiteral(" name=\"#download\"");

WriteLiteral(" id=\"dLink\"");

WriteLiteral(" onclick=\"activeClass(this);\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/icon_dwonload.png\"");

WriteLiteral(" id=\"downloadLink\"");

WriteLiteral(" />\r\n                        <span>Download</span>\r\n                    </a>\r\n   " +
"             </li>\r\n                <li>\r\n                    <a");

WriteLiteral(" name=\"#faq\"");

WriteLiteral(" id=\"faLink\"");

WriteLiteral(" onclick=\"activeClass(this);\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/icon_faq.png\"");

WriteLiteral(" id=\"faqLink\"");

WriteLiteral(" />\r\n                        <span>FAQ</span>\r\n                    </a>\r\n        " +
"        </li>\r\n                <li>\r\n                    <a");

WriteLiteral(" name=\"#aboutUs\"");

WriteLiteral(" id=\"abLink\"");

WriteLiteral(" onclick=\"activeClass(this);\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/icon_aboutus.png\"");

WriteLiteral(" id=\"aboutLink\"");

WriteLiteral(" />\r\n                        <span>About Us</span>\r\n                    </a>\r\n   " +
"             </li>\r\n                <li>\r\n                    <a");

WriteLiteral(" name=\"#contectUs\"");

WriteLiteral(" id=\"cLink\"");

WriteLiteral(" onclick=\"activeClass(this);\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" alt=\"\"");

WriteLiteral(" src=\"/images/icon_contanctus.png\"");

WriteLiteral(" id=\"contactLink\"");

WriteLiteral(" />\r\n                        <span>Contact Us</span>\r\n                    </a>\r\n " +
"               </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <!--FEA" +
"TURE SECTION MOBILE -->\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" id=\"feature-mobile\"");

WriteLiteral(" style=\"z-index: 999\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"max-width: 60rem\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"large-12 featureSection\"");

WriteLiteral(">\r\n                <h1>\r\n                    Features\r\n                </h1>\r\n   " +
"             <div");

WriteLiteral(" style=\"margin: 20px 0 15px 0\"");

WriteLiteral(">\r\n                    <!-- Swiper -->\r\n                    <div");

WriteLiteral(" class=\"swiper-container\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"swiper-wrapper\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_01.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_02.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_03.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_04.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_05.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"swiper-slide\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" src=\"/images/features_06.png\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <!-- Add Pagination -->\r\n                        <div");

WriteLiteral(" class=\"swiper-pagination\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <!-------End--->\r\n");

WriteLiteral("    ");

            
            #line 610 "..\..\Views\Shared\Layouts\CustomMaster.cshtml"
Write(RenderSection("FeatureContent", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 718 "..\..\Views\Shared\Layouts\CustomMaster.cshtml"
Write(RenderSection("DownloadContent", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n    <div class=\"section\" id=\"download-mobile\" style=\"z-index: 999;\">\r\n   " +
"     <div class=\"row\" style=\"height: 100%;\">\r\n            <div class=\"large-12 d" +
"ownloadSection\">\r\n                <h1>\r\n                    Download\r\n          " +
"      </h1>\r\n                <h2 style=\"font-size: 17px;\">\r\n                    " +
"ANYWHERE. ANYTIME. ANY DEVICE.\r\n                </h2>\r\n                <div clas" +
"s=\"large-6 medium-6 small-12 columns\">\r\n                    <div class=\"large-12" +
" medium-12 small-12 columns downloadText\">\r\n                        <p>\r\n       " +
"                     <b>\r\n                                The best way to Learn." +
"&nbsp;English.&nbsp;Fast. is on your device-desktop, Android\r\n                  " +
"              tablet, Android phone, iPad, or iPhone.\r\n                         " +
"   </b>\r\n                        </p>\r\n                        <p>\r\n            " +
"                NYCE makes it easy for you to purchase and download the software" +
". It\'s available on the <span style=\"color: #c0d2ff\">App Store</span> and at <sp" +
"an style=\"color: #c0d2ff\">\r\n                                Google play\r\n       " +
"                     </span>.\r\n                        </p>\r\n                   " +
" </div>\r\n                </div>\r\n                <div class=\"large-12 medium-12 " +
"small-12 columns appImageContainer\">\r\n                    <div class=\"large-6 me" +
"dium-6 small-4 columns \">\r\n                        <a href=\"https://itunes.apple" +
".com/us/app/nycenglish/id1022246281?ls=1&mt=8\" target=\"_blank\"><img alt=\"\" src=\"" +
"/images/button_appstore.png\" class=\"imgmargin\" /></a>\r\n                        <" +
"a href=\"https://play.google.com/store/apps/details?id=com.vidyatech.biz&hl=en\" t" +
"arget=\"_blank\"><img alt=\"\" src=\"/images/button_googleplay.png\" class=\"imgmargin\"" +
" /></a>\r\n                    </div>\r\n                    <div class=\"large-6 med" +
"ium-6 small-8 columns\">\r\n                        <img style=\"\" alt=\"\" src=\"/imag" +
"es/mobile_view.png\" />\r\n                    </div>\r\n                </div>\r\n    " +
"        </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"clearfix\">\r\n    </di" +
"v>\r\n\r\n\r\n\r\n");

WriteLiteral("    ");

            
            #line 812 "..\..\Views\Shared\Layouts\CustomMaster.cshtml"
Write(RenderSection("FAQContent", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral(@"


    <div class=""clearfix"">
    </div>
    <div class=""section"">
        <div class=""row"">
            <div class=""large-12"" style=""padding: 0 40px"">
            </div>
        </div>
    </div>
    <div class=""clearfix"">
    </div>











    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    <div class=\"section\" id=\"footer\" style=\"padding" +
": 20px; background-color: #000000;\r\n            border-color: #333637; color: #6" +
"46464; min-height: 50px;\">\r\n        <div id=\"footerInner\" style=\"width: 65%; mar" +
"gin: 0 auto;\">\r\n            <div style=\"width: auto; height: auto;\">\r\n          " +
"      <img src=\"/images/logo_small_1.png\" />\r\n                <div style=\"float:" +
" right; width: 50%; text-align: right; padding-right: 15px;\">\r\n                 " +
"   <span style=\"font-size: 14px; color: #ffffff\">\r\n                        <a hr" +
"ef=\"termofuse.html\" style=\"text-decoration: none;\r\n                            c" +
"olor: white;\" target=\"_blank\">Legal</a> . <a href=\"privacy.html\" style=\"text-dec" +
"oration: none;\r\n                                color: white;\" target=\"_blank\">P" +
"rivacy</a> </inp>\r\n                    </span>\r\n                </div>\r\n        " +
"    </div>\r\n            <div class=\"socialIconContainer\">\r\n                <div " +
"class=\"socialIcon\">\r\n                    <a href=\"https://www.facebook.com/profi" +
"le.php?id=100009743408473\" onmouseover=\"$(this).find(\'img\').attr(\'src\',\'images/i" +
"con_fb_hover.png\');\" onmouseout=\"$(this).find(\'img\').attr(\'src\',\'images/icon_fb." +
"png\');\">\r\n                        <img src=\"/images/icon_fb.png\" style=\"outline:" +
" none; border: none;\" />\r\n                    </a>\r\n                </div>\r\n    " +
"            <div class=\"socialIcon\">\r\n                    <a href=\"https://www.l" +
"inkedin.com/profile/view?id=428219385&trk=nav_responsive_tab_profile\" onmouseove" +
"r=\"$(this).find(\'img\').attr(\'src\',\'images/icon_in_hover.png\');\" onmouseout=\"$(th" +
"is).find(\'img\').attr(\'src\',\'images/icon_in.png\');\">\r\n                        <im" +
"g src=\"/images/icon_in.png\" style=\"outline: none; border: none;\" />\r\n           " +
"         </a>\r\n                </div>\r\n                <div class=\"socialIcon\">\r" +
"\n                    <a href=\"https://twitter.com/NYCEnglish1\" onmouseover=\"$(th" +
"is).find(\'img\').attr(\'src\',\'images/icon_tw_hover.png\');\" onmouseout=\"$(this).fin" +
"d(\'img\').attr(\'src\',\'images/icon_tw.png\');\">\r\n                        <img src=\"" +
"/images/icon_tw.png\" style=\"outline: none; border: none;\" />\r\n                  " +
"  </a>\r\n                </div>\r\n            </div>\r\n            <div id=\"copyrig" +
"htText\">\r\n                <span style=\"font-size: 12px; color: #ffffff\">\r\n      " +
"              Copyright &#169; 2015 NYC English All\r\n                    Rights " +
"Reserved.\r\n                </span>\r\n                <br />\r\n                <a h" +
"ref=\"http://www.vidyatech.com\" target=\"_blank\" style=\"font-size: 10px; color: gr" +
"ey;\r\n                        text-decoration: none;\">\r\n                    <span" +
" style=\"display: block; margin-top: 10px;\">\r\n                        Developed a" +
"nd\r\n                        Managed by Vidyatech\r\n                    </span>\r\n " +
"               </a>\r\n            </div>\r\n        </div>\r\n        <div id=\"footer" +
"Space\">\r\n            <br />\r\n        </div>\r\n        <script type=\"text/javascri" +
"pt\" src=\"/slick/slick.js\"></script>\r\n        <script>\r\n            var swiper = " +
"new Swiper(\'.swiper-container\', {\r\n                pagination: \'.swiper-paginati" +
"on\',\r\n                paginationClickable: true\r\n            });\r\n\r\n        </sc" +
"ript>\r\n\r\n        <div id=\"modalVideo\" class=\"modal1\">\r\n            <div class=\"m" +
"odal-content\">\r\n                <div class=\"modal-header\">\r\n                    " +
"<a class=\"cross\"></a>\r\n                </div>\r\n                <div class=\"modal" +
"-body\">\r\n                    <video controls class=\"videoplayercls\" id=\"vdo\" pre" +
"load>\r\n                        <source src=\"https://nyceprod.blob.core.windows.n" +
"et/production/videos/corpweb/NYCEng30secPromo.mp4\" type=\"video/mp4\"> Your browse" +
"r does not support HTML5 video.\r\n                    </video>\r\n                <" +
"/div>\r\n                <div class=\"clear\"></div>\r\n            </div>\r\n        </" +
"div>\r\n\r\n        <!-- The Modal -->\r\n        <div");

WriteLiteral(" id=\"modalGetInfo\"");

WriteLiteral(" class=\"modalGetInfo\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modalGetInfo-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modalGetInfo-header\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"cross\"");

WriteLiteral("></a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modalGetInfo-body\"");

WriteLiteral(">\r\n                    <h1>Get Started</h1>.\r\n                    <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/images/img1.png\"");

WriteLiteral(" />\r\n                        <a");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">Placement Test</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/images/img2.png\"");

WriteLiteral(" />\r\n                        <a");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">Login Course</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/images/img3.png\"");

WriteLiteral(" />\r\n                        <a");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">Login Dashboard</a>\r\n                    </div>\r\n                </div>\r\n       " +
"     </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div>\r\n        ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 1108 "..\..\Views\Shared\Layouts\CustomMaster.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n\r\n\r\n    ");

WriteLiteral("\r\n   \r\n\r\n");

        }
    }
}
#pragma warning restore 1591
