#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 29 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 28 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/DefaultLayout.cshtml")]
    public partial class _Views_Shared_Layouts_DefaultLayout_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Core.DataContracts.IPage>
    {
        public _Views_Shared_Layouts_DefaultLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 31 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";
    ViewBag.googleAppid = System.Configuration.ConfigurationManager.AppSettings["googleAppId"];

    ViewBag.facebookid = System.Configuration.ConfigurationManager.AppSettings["facebookAppId"];

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("Styles", () => {

WriteLiteral("    \n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
Write(Html.RenderStyleSheets<InstallationModuleDescriptor>());

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n");

DefineSection("HeadScripts", () => {

WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
Write(RenderSection("HeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/content/styles/bootstrap.css\"");

WriteLiteral(" />\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/jquery.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/js/bootstrap.min.js\"");

WriteLiteral("></script>\n\n\n<div");

WriteLiteral(" class=\"page\"");

WriteLiteral(" style=\"min-width:200px !important;\"");

WriteLiteral(">\n\n    <header");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"clearfix container\"");

WriteLiteral(">\r\n            <div>\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
           Write(RenderSection("CMSHeader", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\n    </header>\n\n    <div");

WriteLiteral(" class=\"page-block container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"learfix container\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 63 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
       Write(RenderSection("CMSMainContent", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 64 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\n\n</div>\n\n<footer");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"clearfix container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 72 "..\..\Views\Shared\Layouts\DefaultLayout.cshtml"
   Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</footer>\n<style>\r\n     ");

WriteLiteral("@media (min-width: 400px) and (max-width: 767px) {\r\n         .container {\r\n      " +
"  width: 400px;\r\n    }\n</style>");

        }
    }
}
#pragma warning restore 1591
