#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/DrVinod_profileTemplate.cshtml")]
    public partial class _Views_Shared_Layouts_DrVinod_profileTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_DrVinod_profileTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta charset=\"utf-" +
"8\" />\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>-->\r\n\r\n");

            
            #line 12 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/jetmenu.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/hover_pack.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.simple-text-rotator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.unveilEffects.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jetmenu.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/application.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"top-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
       Write(RenderSection("CMSHeader1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <header");

WriteLiteral(" id=\"sticky-header\"");

WriteLiteral(" class=\"header-wrapper top-menu\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding-left:3.75%;padding-right:1.75%;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-header clearfix\"");

WriteLiteral(">\r\n\r\n\r\n                <div");

WriteLiteral(" id=\"\"");

WriteLiteral(" style=\"position: relative;display: table;width: 100%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"mob-logoimg\"");

WriteLiteral(" style=\"float:left;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
                   Write(RenderSection("CMSHeader2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"mob-menu\"");

WriteLiteral(" style=\"float:right;position: absolute;bottom: 0px;right: 0;padding-bottom:3%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 109 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
                   Write(RenderSection("CMSHeader3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n\r\n            </div>\r\n   " +
"     </div>\r\n    </header>\r\n</div>\r\n\r\n<div>\r\n    ");

WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" id=\"\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 125 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
       Write(RenderSection("Banner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-top:43px;padding-bottom:30px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container profile-container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\"");

WriteLiteral(">\r\n\r\n\r\n");

WriteLiteral("                    ");

            
            #line 136 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
               Write(RenderSection("Profile_intro_image", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div><!-- end col-lg-6 -->\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteLiteral(" style=\"padding-top:90px;\"");

WriteLiteral(">\r\n                    \r\n                    <div");

WriteLiteral(" style=\"box-sizing: border-box;background-color:#f9f9f9;border:4px solid #e2e2e2;" +
"padding:25px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 142 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
                   Write(RenderSection("Profile_intro_education", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n\r\n                </div><!-- end col-lg-6 -->\r\n  " +
"          </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</div>" +
"\r\n\r\n\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-bottom:40px;padding-top:0px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container profile-container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tab\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 159 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
               Write(RenderSection("Profile-tab-links", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </section>\r\n    </div>\r\n</d" +
"iv>\r\n\r\n\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-bottom:50px;padding-top:0px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container profile-container\"");

WriteLiteral(">\r\n\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Overview\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 219 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
               Write(RenderSection("Profile_Tab_contents_Overview", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Researchexperience\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 320 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
               Write(RenderSection("Profile_Tab_contents_Researchexperience", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Publications\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 325 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
               Write(RenderSection("Profile_Tab_contents_Publications", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" style=\"display:block;float:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 366 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
                   Write(RenderSection("Profile_Downloadlink", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                \r\n       " +
"     </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</div>\r\n\r\n\r" +
"\n\r\n<footer>\r\n    <div>\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n           \r\n");

WriteLiteral("            ");

            
            #line 383 "..\..\Views\Shared\Layouts\DrVinod_profileTemplate.cshtml"
       Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</footer>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
