#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/DrVinod_homepageTemplate.cshtml")]
    public partial class _Views_Shared_Layouts_DrVinod_homepageTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_DrVinod_homepageTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/jetmenu.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/hover_pack.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.simple-text-rotator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.unveilEffects.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jetmenu.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/application.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"top-header\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("            ");

            
            #line 69 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
       Write(RenderSection("CMSHeader1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <header");

WriteLiteral(" id=\"sticky-header\"");

WriteLiteral(" class=\"header-wrapper top-menu\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding-left:3.75%;padding-right:1.75%;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-header clearfix\"");

WriteLiteral(">\r\n \r\n\r\n                <div");

WriteLiteral(" id=\"\"");

WriteLiteral(" style=\"position: relative;display: table;width: 100%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"mob-logoimg\"");

WriteLiteral(" style=\"float:left;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 82 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSHeader2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"mob-menu\"");

WriteLiteral(" style=\"float:right;position: absolute;bottom: 0px;right: 0;padding-bottom:3%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 103 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSHeader3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n\r\n            </div>\r\n   " +
"     </div>\r\n    </header>\r\n</div>\r\n\r\n<div>\r\n    ");

WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"main-content sliders\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" id=\"myCarousel\"");

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 119 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
       Write(RenderSection("CMSSlider", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"CMS_ContentWithRightImage\"");

WriteLiteral(">\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contentwithrightimagebg.png);\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"widget clearfix\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"services_lists\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 184 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                       Write(RenderSection("CMSLeftContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div><!-- services_lists -->\r\n                    </di" +
"v><!-- end widget -->\r\n                </div><!-- end col-lg-6 -->\r\n            " +
"    <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out 0s;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 191 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSLeftContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n      " +
"      </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</div>\r\n\r\n" +
"<div>\r\n\r\n    <section");

WriteLiteral(" id=\"ContentRightCMS\"");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contentwithleftimagebg.png);backgroun" +
"d-size:cover;padding: 55px 0 48px 0;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"general_wrapper clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"ContentRightCMS_img\"");

WriteLiteral(" class=\"col-lg-5 col-md-5 col-sm-5 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"entry effect-slide-right in\"");

WriteLiteral(" data-effect=\"slide-right\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 208 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSRightContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n      " +
"          <div");

WriteLiteral(" class=\"col-lg-7 col-md-7 col-sm-7 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"about_widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 227 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSRightContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n\r\n    " +
"        </div><!-- general -->\r\n        </div><!-- end container -->\r\n    </sect" +
"ion>\r\n\r\n</div>\r\n\r\n<div>\r\n    <section");

WriteLiteral(" class=\"section-whitenopadding\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" data-effect=\"slide-right\"");

WriteLiteral(" class=\"effect-slide-right in\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 243 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
               Write(RenderSection("CMSAccordian1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div><!-- end col-lg-6 -->\r\n            <d" +
"iv");

WriteLiteral(" id=\"myths\"");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"about_widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"heading-container\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"heading\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 253 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                       Write(RenderSection("CMSAccordian2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    ");

WriteLiteral("\r\n                </div>\r\n                    <div");

WriteLiteral(" class=\"panel-group\"");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(" style=\"width:85%; margin-bottom:0px;margin-top:5%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 278 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSAccordian3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <!-- end panel -->\r\n                    </div><!-- pane" +
"l-group -->\r\n                    <div");

WriteLiteral(" id=\"myths-linkto-about\"");

WriteLiteral(" style=\"text-align:right;padding:10px;color:#129cd2;font-size:14px;margin-right:1" +
"4%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 286 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
                   Write(RenderSection("CMSAccordian4", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end about widget -->\r\n  " +
"          </div><!-- end col-lg-6 -->\r\n\r\n        </div><!-- general -->\r\n    </s" +
"ection>\r\n\r\n</div>\r\n\r\n<div>\r\n\r\n    <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contact_blueband.png);background-size" +
":cover;padding-bottom:40px\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 304 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
               Write(RenderSection("CMSContact1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"home-callforactionbtn\"");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\"");

WriteLiteral(" style=\"margin-top:4%;text-align:right;padding-right:3%!important;\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 309 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
           Write(RenderSection("CMSContact2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </section>\r\n\r\n</div>\r\n\r\n<div>\r\n    <sec" +
"tion");

WriteLiteral(" class=\"section-portfolio\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"fullwidth-post-wrapper col-lg-12\"");

WriteLiteral(">\r\n                <div>\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 330 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
               Write(RenderSection("CMSPortfolio1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <nav");

WriteLiteral(" class=\"portfolio-filter clearfix\"");

WriteLiteral(" style=\"margin: 31px 0px 22px;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 339 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
               Write(RenderSection("CMSPortfolio2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </nav>\r\n                <div");

WriteLiteral(" class=\"row portfolio_wrapper clearfix isotope\"");

WriteLiteral(" style=\"position: relative; overflow: hidden; height: 351px;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 379 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
               Write(RenderSection("CMSPortfolio3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div><!-- end portfolio_wrapper -->\r\n            </div><!-- fu" +
"llwidth-post-wrapper -->\r\n        </div><!-- end container -->\r\n    </section>\r\n" +
"</div>\r\n\r\n<footer>\r\n    <div>\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 400 "..\..\Views\Shared\Layouts\DrVinod_homepageTemplate.cshtml"
       Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</footer>\r\n");

        }
    }
}
#pragma warning restore 1591
