#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
    using BetterCms.Module.Blog.Helpers.Extensions;
    
    #line default
    #line hidden
    
    #line 31 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
    using BetterCms.Module.Pages.Helpers.Extensions;
    
    #line default
    #line hidden
    
    #line 30 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/ExtensionsLayout.cshtml")]
    public partial class _Views_Shared_Layouts_ExtensionsLayout_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel>
    {
        public _Views_Shared_Layouts_ExtensionsLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("\n");

            
            #line 35 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("Styles", () => {

WriteLiteral("    \n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
Write(Html.RenderStyleSheets<InstallationModuleDescriptor>());

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n");

DefineSection("HeadScripts", () => {

WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 45 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
Write(RenderSection("HeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n<div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\n\n    <header");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n        </div>\n    </header>\n\n    <div");

WriteLiteral(" class=\"page-block\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n            <div>\n                <strong>[Obsolete] Page image: </strong> ");

            
            #line 58 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                    Write(Model.GetPageImage());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>[Obsolete] Page featured image: </strong> ");

            
            #line 59 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                             Write(Model.GetPageFeaturedImage());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>[Obsolete] Page secondary image: </strong> ");

            
            #line 60 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                              Write(Model.GetPageSecondaryImage());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>[Obsolete] Page tags: </strong> ");

            
            #line 61 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                   Write(Model.GetPageTags());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>PageViewModel: </strong> ");

            
            #line 62 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                            Write(Model.GetPageModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>MainImageViewModel: </strong> ");

            
            #line 63 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                 Write(Model.GetPageMainImageModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>FeaturedImageViewModel: </strong> ");

            
            #line 64 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                     Write(Model.GetPageSecondaryImageModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>SecondaryImageViewModel: </strong> ");

            
            #line 65 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                      Write(Model.GetPageFeaturedImageModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>CategoryViewModel: </strong> ");

            
            #line 66 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                Write(Model.GetPageCategoryModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>Tags: </strong> ");

            
            #line 67 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                   Write(Model.GetPageTagsList());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                \n                <strong>[Obsolete] Blog author name: </st" +
"rong> ");

            
            #line 69 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                          Write(Model.GetBlogPostAuthorName());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>[Obsolete] Blog live from date: </strong> ");

            
            #line 70 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                             Write(Model.GetBlogPostLiveFromDate());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>[Obsolete] Blog live to date: </strong> ");

            
            #line 71 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                           Write(Model.GetBlogPostLiveToDate());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>IsBlogPost: </strong> ");

            
            #line 72 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                         Write(Model.IsBlogPost());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>IsBlogPostActive: </strong> ");

            
            #line 73 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                               Write(Model.IsBlogPostActive());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>BlogPostViewModel: </strong> ");

            
            #line 74 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                Write(Model.GetBlogPostModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n                <strong>BlogPostAuthorViewModel: </strong> ");

            
            #line 75 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
                                                      Write(Model.GetBlogPostAuthorModel());

            
            #line default
            #line hidden
WriteLiteral("<br />\n            </div>\n");

WriteLiteral("            ");

            
            #line 77 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
       Write(RenderSection("CMSMainContent", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 78 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n    </div>\n\n</div>\n\n<footer");

WriteLiteral(" class=\"page-footer\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 86 "..\..\Views\Shared\Layouts\ExtensionsLayout.cshtml"
   Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</footer>\n");

        }
    }
}
#pragma warning restore 1591
