#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/FourSectionLayout.cshtml")]
    public partial class _Views_Shared_Layouts_FourSectionLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_FourSectionLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/content/styles/bootstrap.css\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/jquery.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/js/bootstrap.min.js\"");

WriteLiteral("></script>\r\n<header>\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
   Write(RenderSection("CMSHeader", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</header>\r\n\r\n<div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
Write(RenderSection("CMSMainContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
Write(RenderSection("CMSMainContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n   \r\n</div>\r\n\r\n\r\n<footer>\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\Shared\Layouts\FourSectionLayout.cshtml"
   Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</footer>\r\n");

        }
    }
}
#pragma warning restore 1591
