#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 29 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 28 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/OptionsLayout.cshtml")]
    public partial class _Views_Shared_Layouts_OptionsLayout_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel>
    {
        public _Views_Shared_Layouts_OptionsLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("\n");

            
            #line 33 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("Styles", () => {

WriteLiteral("    \n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
Write(Html.RenderStyleSheets<InstallationModuleDescriptor>());

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n");

DefineSection("HeadScripts", () => {

WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
Write(RenderSection("HeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n<div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\n\n    <header");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n            <div>\n");

            
            #line 51 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                  
                if (Model != null && Model.Options != null)
                {
                    foreach (var option in Model.Options)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <strong>Option \"");

            
            #line 56 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                   Write(option.Key);

            
            #line default
            #line hidden
WriteLiteral("\" Type:</strong> ");

            
            #line 56 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                                                    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                                                Write(option.Value != null ? option.Value.GetType().ToString() : string.Empty);

            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                                                                                                                              

            
            #line default
            #line hidden
WriteLiteral("                        <strong>; Value: </strong>\n");

            
            #line 58 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                           Write(option.Value);

            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                                                             

            
            #line default
            #line hidden
WriteLiteral("                        <br />\n");

            
            #line 60 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
                    }
                }
            
            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </header>\n\n    <div");

WriteLiteral(" class=\"page-block\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n");

WriteLiteral("            ");

            
            #line 69 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
       Write(RenderSection("CMSMainContent", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 70 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n    </div>\n\n</div>\n\n<footer");

WriteLiteral(" class=\"page-footer\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 78 "..\..\Views\Shared\Layouts\OptionsLayout.cshtml"
   Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</footer>\n");

        }
    }
}
#pragma warning restore 1591
