#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/SampleVinod.cshtml")]
    public partial class _Views_Shared_Layouts_SampleVinod_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_SampleVinod_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/jetmenu.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/hover_pack.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jetmenu.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/application.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.simple-text-rotator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.unveilEffects.js\"");

WriteLiteral("></script>\r\n\r\n<div>\r\n    <div");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("            ");

            
            #line 67 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
       Write(RenderSection("CMSHeader1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <header");

WriteLiteral(" class=\"header-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-header clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" class=\"affix-top\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-3 col-md-3 col-sm-12 title-area pull-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(" id=\"title\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 79 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                       Write(RenderSection("CMSHeader2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div><!-- site title -->\r\n                    </div><!" +
"-- title area -->\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-lg-9 col-md-9 col-sm-12\"");

WriteLiteral(" style=\"margin-top:30px\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 98 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSHeader3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </header>\r\n</div>\r\n\r\n<div>\r\n    ");

WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"main-content sliders\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" id=\"myCarousel\"");

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 112 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
           Write(RenderSection("CMSSlider", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n    </div>\r\n</div>\r\n\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contentwithrightimagebg.png);\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-7 col-md-7 col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"widget clearfix\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"services_lists\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 177 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                       Write(RenderSection("CMSLeftContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div><!-- services_lists -->\r\n                    </di" +
"v><!-- end widget -->\r\n                </div><!-- end col-lg-6 -->\r\n            " +
"    <div");

WriteLiteral(" class=\"col-lg-5 col-md-5 col-sm-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out 0s;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 184 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSLeftContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n      " +
"      </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</div>\r\n\r\n" +
"<div>\r\n\r\n    <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contentwithleftimagebg.png);\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"general_wrapper clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-5 col-md-5 col-sm-5 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"entry effect-slide-right in\"");

WriteLiteral(" data-effect=\"slide-right\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 201 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSRightContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n      " +
"          <div");

WriteLiteral(" class=\"col-lg-7 col-md-7 col-sm-7 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"about_widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 220 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSRightContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end col-lg-6 -->\r\n\r\n    " +
"        </div><!-- general -->\r\n        </div><!-- end container -->\r\n    </sect" +
"ion>\r\n\r\n</div>\r\n\r\n<div>\r\n    <section");

WriteLiteral(" class=\"section-whitenopadding\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" data-effect=\"slide-right\"");

WriteLiteral(" class=\"effect-slide-right in\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 236 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
               Write(RenderSection("CMSAccordian1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div><!-- end col-lg-6 -->\r\n            <d" +
"iv");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"about_widget effect-slide-left in\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(" style=\"transition: all 0.7s ease-in-out;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"border-left:2px solid black;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"padding-left:10px;\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 245 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                       Write(RenderSection("CMSAccordian2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"panel-group\"");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(" style=\"width:85%; margin-bottom:0px;margin-top:5%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 269 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSAccordian3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <!-- end panel -->\r\n                    </div><!-- pane" +
"l-group -->\r\n                    <div");

WriteLiteral(" style=\"text-align:right;padding:10px;color:#129cd2;font-size:14px;margin-right:1" +
"4%;\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 277 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
                   Write(RenderSection("CMSAccordian4", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div><!-- end about widget -->\r\n  " +
"          </div><!-- end col-lg-6 -->\r\n\r\n        </div><!-- general -->\r\n    </s" +
"ection>\r\n\r\n</div>\r\n\r\n<div>\r\n\r\n    <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"background:url(/uploads/widgetimage/contact_blueband.png);background-size" +
":cover;padding-bottom:40px\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 295 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
               Write(RenderSection("CMSContact1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\"");

WriteLiteral(" style=\"margin-top:2%;\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 300 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
           Write(RenderSection("CMSContact2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </section>\r\n\r\n</div>\r\n\r\n<div>\r\n    <sec" +
"tion");

WriteLiteral(" class=\"section-portfolio\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"fullwidth-post-wrapper col-lg-12\"");

WriteLiteral(">\r\n                <div>\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 321 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
               Write(RenderSection("CMSPortfolio1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <nav");

WriteLiteral(" class=\"portfolio-filter clearfix\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 330 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
               Write(RenderSection("CMSPortfolio2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </nav>\r\n                <div");

WriteLiteral(" class=\"row portfolio_wrapper clearfix isotope\"");

WriteLiteral(" style=\"position: relative; overflow: hidden; height: 351px;\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 370 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
               Write(RenderSection("CMSPortfolio3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div><!-- end portfolio_wrapper -->\r\n            </div><!-- fu" +
"llwidth-post-wrapper -->\r\n        </div><!-- end container -->\r\n    </section>\r\n" +
"</div>\r\n\r\n<footer>\r\n    <div>\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 391 "..\..\Views\Shared\Layouts\SampleVinod.cshtml"
       Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</footer>\r\n");

        }
    }
}
#pragma warning restore 1591
