#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 29 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 28 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/TestLayout.cshtml")]
    public partial class _Views_Shared_Layouts_TestLayout_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel>
    {
        public _Views_Shared_Layouts_TestLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("\n");

            
            #line 33 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("Styles", () => {

WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
Write(Html.RenderStyleSheets<InstallationModuleDescriptor>());

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n");

DefineSection("HeadScripts", () => {

WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 43 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
Write(RenderSection("HeadScripts", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("\n");

WriteLiteral("\n\n<div");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\n\n    <header");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
       Write(RenderSection("CMSHeader", false));

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n    </header>\n\n    <div");

WriteLiteral(" class=\"page-block\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n            oioioi\n");

WriteLiteral("            ");

            
            #line 75 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
       Write(RenderSection("CMSMainContent", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 76 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n    </div>\n\n</div>\n\n<footer");

WriteLiteral(" class=\"page-footer\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"page-frame bcms-clearfix\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 84 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
   Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</footer>\n\n");

DefineSection("Scripts", () => {

WriteLiteral("\n    <script");

WriteLiteral(" src=\"https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\n");

});

DefineSection("BodyTag", () => {

WriteLiteral("\n    <!--[if lte IE 8]>\n    <body class=\"ie8 fixed-nav faded\"");

            
            #line 93 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
                                Write(Html.RenderBodyAttributes());

            
            #line default
            #line hidden
WriteLiteral("><![endif]-->\n    <!--[if IE 9]>\n    <b\n    ody class=\"ie9 fixed-nav faded\"");

            
            #line 96 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
                              Write(Html.RenderBodyAttributes());

            
            #line default
            #line hidden
WriteLiteral("><![endif]-->\n    <!--[if !IE]><!-\n    ->  <body class=\"fixed-nav<body class=\"fix" +
"ed-nav fa\n    <body class=\" fixed-nav faded\" ");

            
            #line 99 "..\..\Views\Shared\Layouts\TestLayout.cshtml"
                              Write(Html.RenderBodyAttributes());

            
            #line default
            #line hidden
WriteLiteral(">\n        <!--<![endif]-->\n");

});

        }
    }
}
#pragma warning restore 1591
