#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/VidyatechCaseStudiesPage.cshtml")]
    public partial class _Views_Shared_Layouts_VidyatechCaseStudiesPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_VidyatechCaseStudiesPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("<!doctype html>\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" style=\"overflow-x:hidden\"");

WriteLiteral(">\r\n<head>\r\n\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/new.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"../images/Vidya.ico\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery-3.2.1.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.carouFredSel.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/custom.js \"");

WriteLiteral("></script>\r\n\r\n    <title>Mission Dashboard for Government of India</title>\r\n\r\n\r\n " +
"   <style>\r\n        blockquote {\r\n            font-family: Arial,Georgia,serif;\r" +
"\n            font-size: 18px;\r\n            color: #7f7f7f;\r\n            line-hei" +
"ght: 1.45;\r\n            padding: 0em 40px;\r\n            position: relative;\r\n   " +
"     }\r\n\r\n            blockquote::before {\r\n                color: #f79646;\r\n   " +
"             content: \"“\";\r\n                display: block;\r\n                fon" +
"t-size: 60px;\r\n                left: -1px;\r\n                position: absolute;\r" +
"\n                top: -10px;\r\n            }\r\n\r\n            blockquote::after {\r\n" +
"                color: #f79646;\r\n                content: \"”\";\r\n                " +
"display: block;\r\n                font-size: 60px;\r\n                right: 10px;\r" +
"\n                position: absolute;\r\n                bottom: -10px;\r\n          " +
"  }\r\n\r\n            blockquote cite::before {\r\n                content: \"—\";\r\n   " +
"         }\r\n\r\n            blockquote cite {\r\n                color: #4f81bd;\r\n  " +
"              display: block;\r\n                font-size: 12px;\r\n               " +
" margin-top: 5px;\r\n            }\r\n\r\n        .hero {\r\n            position: relat" +
"ive;\r\n            width: 100% !important;\r\n        }\r\n\r\n        .saf {\r\n        " +
"    background-color: #e9e9e9;\r\n        }\r\n\r\n        .blu {\r\n            backgro" +
"und-color: #31859c;\r\n        }\r\n\r\n        .hero:after {\r\n            content: \'\'" +
";\r\n            position: absolute;\r\n            top: 0%;\r\n            left: 50%;" +
"\r\n            margin-left: -25px;\r\n            width: 0;\r\n            height: 0;" +
"\r\n            border-top: solid 25px white;\r\n            border-left: solid 25px" +
" transparent;\r\n            border-right: solid 25px transparent;\r\n        }\r\n\r\n " +
"       p {\r\n            line-height: 1.8em;\r\n            margin-bottom: 10px;\r\n " +
"       }\r\n\r\n        li {\r\n            margin-left: 20px;\r\n        }\r\n\r\n        f" +
"ieldset {\r\n            border: 3px solid white;\r\n            min-width: 0;\r\n    " +
"        width: 100%;\r\n        }\r\n\r\n            fieldset legend {\r\n              " +
"  margin-left: 10px;\r\n                padding-left: 10px;\r\n                paddi" +
"ng-right: 10px;\r\n                color: white;\r\n                margin-right: 11" +
"0px;\r\n                background: none;\r\n            }\r\n\r\n        h4 {\r\n        " +
"    color: white;\r\n            padding: 5% 5% 6% 5%;\r\n            text-transform" +
": uppercase;\r\n        }\r\n    </style>\r\n    <script>\r\n        $(function () {\r\n  " +
"          var $c = $(\'#carousel\'),\r\n                $w = $(window);\r\n\r\n         " +
"   $c.carouFredSel({\r\n                responsive: true,\r\n                align: " +
"true,\r\n                items: {\r\n                    visible: {\r\n               " +
"         min: 1,\r\n                        max: 5\r\n                    }\r\n       " +
"         },\r\n                scroll: {\r\n                    items: 1,\r\n         " +
"           duration: 8000,\r\n                    timeoutDuration: 0,\r\n           " +
"         easing: \'linear\',\r\n                    pauseOnHover: \'immediate\',\r\n    " +
"                fx: \'directscroll\'\r\n                }\r\n            });\r\n        " +
"});\r\n    </script>\r\n\r\n</head>\r\n<body>\r\n    <div>\r\n        <section>\r\n           " +
" <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 157 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
           Write(RenderSection("CMSSectionBanner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>\r\n        <section" +
">\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin-top:4%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"medium-6 columns liner\"");

WriteLiteral(" style=\"padding-top:3%;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 167 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSection1Content1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"medium-6 columns \"");

WriteLiteral(">\r\n                            <blockquote>\r\n");

WriteLiteral("                                ");

            
            #line 171 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                           Write(RenderSection("CMSSection1Content2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </blockquote>\r\n                        </div>\r\n    " +
"                </div>\r\n                </div>\r\n            </div>\r\n        </se" +
"ction>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin-top:4%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 185 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSection2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>\r\n        <sec" +
"tion>\r\n            <div");

WriteLiteral(" class=\"section hero saf\"");

WriteLiteral(" style=\"padding-bottom:2%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"margin-top:50px;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"medium-3 columns\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 199 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                           Write(RenderSection("CMSSection3Content1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"medium-9 columns\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                            ");

            
            #line 204 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSection3Content2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>\r\n        <sec" +
"tion>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"margin-top:4%;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"medium-3 columns\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 218 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                           Write(RenderSection("CMSSection4Content1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"medium-9 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 222 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSection4Content2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>\r\n        <sec" +
"tion>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin-top:4%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 235 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSection5", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>\r\n        <sec" +
"tion>\r\n            <div");

WriteLiteral(" class=\"section hero blu\"");

WriteLiteral(" style=\"padding-bottom:2%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"margin-top:50px;color:white;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 247 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                   Write(RenderSection("CMSSection6", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </section>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin-top:1%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                            ");

            
            #line 260 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                       Write(RenderSection("CMSSectionFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n            </section></div>\r\n   <div>\r\n            <se" +
"ction>\r\n                <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin-top:4%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n                            \r\n");

WriteLiteral("                                    ");

            
            #line 272 "..\..\Views\Shared\Layouts\VidyatechCaseStudiesPage.cshtml"
                               Write(RenderSection("CMSSectionPreFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                              \r\n                        </div>\r\n               " +
"     </div>\r\n                </div>\r\n            </section>\r\n       </div>\r\n</bo" +
"dy>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
