#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/VidyatechHomePage.cshtml")]
    public partial class _Views_Shared_Layouts_VidyatechHomePage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_VidyatechHomePage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("<!doctype html>\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/new.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/banner-slider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/coolC.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/flexisel.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/home.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/social.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/slick.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery-3.2.1.min.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://www.google.com/jsapi?key=[apikey]\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.j" +
"s\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/additional-methods.js" +
"\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/banner-slider.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.easing.1.3.js\"");

WriteLiteral("></script>\r\n    <!--script type=\"text/javascript\" src=\"js/jquery.mobile.customize" +
"d.min.js\"></script-->\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.nav.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.scrollTo.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.flexisel.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/slick.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/modernizr.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/respond.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.carouFredSel-6.0.4-packed.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.placeholder.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.h5validate.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/custom.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.sticky.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        //document.write(\'<style type=\"text/css\">body {visibility:hidden;}</st" +
"yle>\');\r\n    </script>\r\n \r\n    <script>\r\n        var menuOpen = (function () {\r\n" +
"            jQuery(\"#show\").click(function () {\r\n\r\n                jQuery(\"#menu" +
"Option\").slideToggle(\"fast\");\r\n            });\r\n        });\r\n    </script>\r\n    " +
"<script>\r\n        (function (i, s, o, g, r, a, m) {\r\n            i[\'GoogleAnalyt" +
"icsObject\'] = r;\r\n            i[r] = i[r] || function () {\r\n                (i[r" +
"].q = i[r].q || []).push(arguments)\r\n            }, i[r].l = 1 * new Date();\r\n  " +
"          a = s.createElement(o),\r\n                m = s.getElementsByTagName(o)" +
"[0];\r\n            a.async = 1;\r\n            a.src = g;\r\n            m.parentNode" +
".insertBefore(a, m)\r\n        })(window, document, \'script\', \'//www.google-analyt" +
"ics.com/analytics.js\', \'ga\');\r\n\r\n        ga(\'create\', \'UA-54469785-1\', \'auto\');\r" +
"\n        ga(\'require\', \'displayfeatures\');\r\n        ga(\'require\', \'linkid\', \'lin" +
"kid.js\');\r\n        ga(\'send\', \'pageview\', location.pathname + location.search + " +
"location.hash);\r\n\r\n        setTimeout(\"ga(\'send\',\'event\',\'Profitable Engagement\'" +
",\'time on page more than 1 minute\')\", 60000);\r\n\r\n\r\n\r\n        $(document).ready(f" +
"unction () {\r\n\r\n\r\n            var x = location.hash;\r\n\r\n            if (x == \"#s" +
"ervices\") {\r\n                $(\'#home\').removeClass(\"active\");\r\n                " +
"$(\'#serviceli\').addClass(\"active\");\r\n            } else if (x == \"#contact\") {\r\n" +
"                $(\'#home\').removeClass(\"active\");\r\n                $(\'#contactli" +
"\').addClass(\"active\");\r\n\r\n            } else if (x == \"#testimonial\") {\r\n       " +
"         $(\'#home\').removeClass(\"active\");\r\n                $(\'#testimonialli\')." +
"addClass(\"active\");\r\n\r\n            } else if (x == \"#team\") {\r\n                $" +
"(\'#home\').removeClass(\"active\");\r\n                $(\'#teamli\').addClass(\"active\"" +
");\r\n\r\n            }\r\n\r\n        });\r\n    </script>\r\n\r\n    <script");

WriteLiteral(" src=\'https://www.google.com/recaptcha/api.js\'");

WriteLiteral("></script>\r\n\r\n</head>\r\n\r\n<body>\r\n    <!----->\r\n    <!--\r\n      <div id=\"preloader" +
"\">\r\n          <div id=\"status\"></div>\r\n      </div>\r\n\r\n      <div class=\"clearfi" +
"x\"></div>\r\n      <!--NEW MENU CODE -->\r\n    <div>\r\n        <section>\r\n          " +
"  <nav");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 119 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
           Write(RenderSection("CMSSectionHeader", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </nav>\r\n        </section>\r\n    </div>\r\n    <!---- NEW MENU CODE EN" +
"DS -->\r\n    <div");

WriteLiteral(" class=\"clearfix anchor\"");

WriteLiteral(" id=\"home-top\"");

WriteLiteral("></div>\r\n  <div> <section>\r\n        <div");

WriteLiteral(" id=\"bannerSlider\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 127 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
       Write(RenderSection("CMSSectionBannerSlider", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </section></div>\r\n   <div> <section>\r\n        <marquee");

WriteLiteral(" id=\'scroll_news\'");

WriteLiteral(" style=\"background-color:#ffce2d;clear:both;\"");

WriteLiteral(" onmouseover=\"this.setAttribute(\'scrollamount\', 0, 0);\"");

WriteLiteral(" onmouseout=\"this.setAttribute(\'scrollamount\', 6, 0);\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 132 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
       Write(RenderSection("CMSSectionMarqueeText", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </marquee>\r\n    </section></div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" id=\"services\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <!-- Services Column Starts he" +
"re  -->\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding-top:55px;padding-bottom:45px;\"");

WriteLiteral(">\r\n                <!-- Section For Services -->\r\n");

WriteLiteral("                ");

            
            #line 141 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
           Write(RenderSection("CMSSectionServices", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <!-- main large-12 End -->\r\n            </div>\r\n            <!-" +
"- Row End -->\r\n\r\n\r\n        </section>\r\n    </div>\r\n    <!-- Section For Services" +
" End -->\r\n    <!-- Services Column ends here  -->\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" id=\"casestudies\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:45px 0;background-color:#e6e6e6;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(" style=\"padding:0 55px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 158 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                   Write(RenderSection("CMSSectionCaseStudies", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </section>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" id=\"testimonial\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background: url(/uploads/Vidyatech/Testimonial/testimonials_bg3.jpg); bac" +
"kground-size: cover; padding: 45px 0 60px 0;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(" style=\"color:white;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 170 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                   Write(RenderSection("CMSSectionTestimonial", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n     " +
"   </section>\r\n    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" id=\"team\"");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:45px 0;margin-top:20px;padding-bottom:0;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"padding:0 40px\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 185 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                   Write(RenderSection("CMSSectionLeadership", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n     " +
"   </section>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"contact\"");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:55px 0;background-color:#E7EFF2;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 198 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                   Write(RenderSection("CMSSectionContactUs", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </section>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:45px 0;background-color:white\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 209 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                   Write(RenderSection("CMSSectionMarquee", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                    </div>\r\n                </div>\r\n            </div>\r\n     " +
"   </section>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color:#2e3133;padding:45px 0\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 222 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 225 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 228 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 231 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                       Write(RenderSection("CMSSectionFooterSectionLogo", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns end\"");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n                            \r\n");

WriteLiteral("                                    ");

            
            #line 235 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
                               Write(RenderSection("CMSSectionFooterSectionSlider", false));

            
            #line default
            #line hidden
WriteLiteral(@"
                                   
                                </div>
                                <!--<div class=""large-12 columns"">
             <div class=""socialmedia"">
                <a href=""https://www.facebook.com/Vidyatech"" target=""_blank""><img src=""images/social/fb.png"" /></a>
                <a href=""https://plus.google.com/114894168344443802562/about"" target=""_blank""><img src=""images/social/gplus.png"" /></a>
                <a href=""http://www.linkedin.com/company/vidyatech"" target=""_blank""><img src=""images/social/in.png"" /></a>
                <a href=""https://twitter.com/Quiz_Magic"" target=""_blank""><img src=""images/social/twitter.png"" /></a>
                <a href=""http://www.youtube.com/user/proofguru"" target=""_blank""><img src=""images/social/youtube.png"" /></a>
             </div>
             </div>-->

                            </div>
                        </div>
            </div>
        </section>
    </div>
    <footer");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color: #222526;border-color: #333637;color: #646464;min-height" +
": 50px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"margin: 18px auto 0; margin-top:30px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 256 "..\..\Views\Shared\Layouts\VidyatechHomePage.cshtml"
           Write(RenderSection("CMSSectionPreFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </footer>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n" +
"\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    <!------>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-11012032-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
    </script>

    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        setTimeout(function () {
            jQuery(document).ready(function ($) {
                $('body').css({
                    'visibility': 'visible'
                });
            });
        }, 400);
    </script>
    <script>
        jQuery(document).ready(function () {
            var hashtag = /#\S+/
            jQuery('.menu li a').click(function () {
                var match = jQuery(this).attr('href').match(hashtag);
                ga('send', 'pageview', '/' + match[0]);
            })
        });
    </script>


    <!--   CAPTCHA Scripts       -->
    <script");

WriteLiteral(" language=\'JavaScript\'");

WriteLiteral(" type=\'text/javascript\'");

WriteLiteral(@">
        function refreshCaptcha() {
            var img = document.images['captchaimg'];
            img.src = img.src.substring(0, img.src.lastIndexOf(""?"")) + ""?rand="" + Math.random() * 1000;
        }
    </script>

    <script>
        // $(document).mouseup(function (e)
        // {
        // var container = $(""#nav"");
        // if (!container.is(e.target) // if the target of the click isn't the container...
        // && container.has(e.target).length === 0) // ... nor a descendant of the container
        // {
        // if($('#menuOption').css('display') == 'block')
        // {
        // $(""#menuOption"").css(""display"",""none"");
        // ($(""#nav"").removeClass(""active""));
        // }


        // }

        // });
    </script>
</body>

</html>");

        }
    }
}
#pragma warning restore 1591
