#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/VidyatechCareersPage.cshtml")]
    public partial class _Views_Shared_Layouts_VidyatechCareersPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_VidyatechCareersPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("<!doctype html>\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" style=\"overflow-x:hidden\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-store\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <title>Careers</title>\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"images/Vidya.ico\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(@" content=""Vidyatech provides custom software services for building, migrating and maintaining Internet / Cloud based systems. We specialize in content technologies and have extensive experience in Collaborative Content Development, Content Analytics, Social Media, Mobile Devices  and Content Security.""");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(@" content=""Custom Application Development, Mobile Application Development, SharePoint Application Development, Content Migration, Cloud Computing, Web Application Development, Content Localization, Software Testing, Business Intelligence, Content Management, CMS Customization, Legacy System Migration, Content Analytics, Social Media, Content Security""");

WriteLiteral(" />\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"https://www.google.com/jsapi\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"http://www.google.com/uds/solutions/dynamicfeed/gfdynamicfeedcontrol.js\"");

WriteLiteral("\r\n            type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n            \r\n\r\n    </style>\r\n\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/new.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/coolC.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/flexisel.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/home.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/social.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/slick.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/camara.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/print.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery-1.7.1.min.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        //document.write(\'<style type=\"text/css\">body {visibility:hidden;}</st" +
"yle>\');\r\n\r\n    </script>\r\n    <script>\r\n        (function (i, s, o, g, r, a, m) " +
"{\r\n            i[\'GoogleAnalyticsObject\'] = r; i[r] = i[r] || function () {\r\n   " +
"             (i[r].q = i[r].q || []).push(arguments)\r\n            }, i[r].l = 1 " +
"* new Date(); a = s.createElement(o),\r\n            m = s.getElementsByTagName(o)" +
"[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)\r\n        })(window," +
" document, \'script\', \'//www.google-analytics.com/analytics.js\', \'ga\');\r\n\r\n      " +
"  ga(\'create\', \'UA-54469785-1\', \'auto\');\r\n        ga(\'require\', \'displayfeatures" +
"\');\r\n        ga(\'require\', \'linkid\', \'linkid.js\');\r\n        ga(\'send\', \'pageview" +
"\', location.pathname + location.search + location.hash);\r\n\r\n        setTimeout(\"" +
"ga(\'send\',\'event\',\'Profitable Engagement\',\'time on page more than 1 minute\')\", 6" +
"0000);\r\n\r\n\r\n\r\n        $(document).ready(function () {\r\n\r\n\r\n            var x = l" +
"ocation.hash;\r\n\r\n            if (x == \"#services\") {\r\n                $(\'#home\')" +
".removeClass(\"active\");\r\n                $(\'#serviceli\').addClass(\"active\");\r\n  " +
"          }\r\n            else if (x == \"#contact\") {\r\n                $(\'#home\')" +
".removeClass(\"active\");\r\n                $(\'#contactli\').addClass(\"active\");\r\n\r\n" +
"            }\r\n            else if (x == \"#testimonial\") {\r\n                $(\'#" +
"home\').removeClass(\"active\");\r\n                $(\'#testimonialli\').addClass(\"act" +
"ive\");\r\n\r\n            }\r\n            else if (x == \"#team\") {\r\n                $" +
"(\'#home\').removeClass(\"active\");\r\n                $(\'#teamli\').addClass(\"active\"" +
");\r\n\r\n            }\r\n\r\n        });\r\n        /* UNCOMMENT IF USING OLD MENU BAR -" +
"--------------------------\r\n        function changeArrowImageRed(){\r\n           " +
" document.getElementById(\"arrow\").src =\"images/arrow2.png\";\r\n        }\r\n        " +
"function changeArrowImage(){\r\n\r\n            var elem = document.getElementById(\'" +
"serviceli\');\r\n            var currentClass = elem.className;\r\n            if(cur" +
"rentClass == \"current\")\r\n            {\r\n                document.getElementById(" +
"\"arrow\").src = \"images/arrow2.png\";\r\n            }\r\n            else\r\n          " +
"  {\r\n            document.getElementById(\"arrow\").src = \"images/arrow.png\";\r\n   " +
"         }\r\n        }\r\n        function changeImage(obj)\r\n        {\r\n           " +
" var className = $(obj).attr(\"name\");\r\n            var id = obj.id;\r\n           " +
" if(className == \"service\" && id == \"serviceli\")\t{\r\n                document.get" +
"ElementById(\"arrow\").src = \"images/arrow2.png\";\r\n                $(\'#ServicesID\'" +
").removeAttr(\'onmouseout\');\r\n                $(\".target li\").live( \"click\", func" +
"tion(event){\r\n                var c = console.log(event.currentTarget);\r\n       " +
"         //alert(c);\r\n        });\r\n            }\r\n            else\r\n            " +
"{\r\n\r\n                document.getElementById(\"arrow\").src = \"images/arrow.png\";\r" +
"\n                //$(\'#ServicesID\').addAttr(\'onmouseout\');\r\n\r\n            }\r\n   " +
"     }\r\n        UNCOMMENT IF USING OLD MENU BAR*/\r\n    </script>\r\n\r\n\r\n\r\n\r\n\r\n</he" +
"ad>\r\n<body>\r\n    <!----->\r\n    <!--\r\n      <div id=\"preloader\">\r\n          <div " +
"id=\"status\"></div>\r\n      </div>\r\n\r\n      <div class=\"clearfix\"></div>\r\n      <!" +
"--NEW MENU CODE -->\r\n    <div>\r\n        <section>\r\n            <nav");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 151 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
           Write(RenderSection("CMSSectionHeader", false));

            
            #line default
            #line hidden
WriteLiteral(@"
            </nav>
        </section>
    </div>
    <!---- NEW MENU CODE ENDS -->
    <script>
        var menuOpen = (function () {
            jQuery(""#show"").click(function () {
                jQuery(""#menuOption"").slideToggle(""fast"");
                jQuery(""#menuOption"").css(""overflow-y"", ""scroll"");
            });
            /*
            jQuery('#serviceli').hover(function () {
                jQuery('#submenu').slideDown(""slow"");

                });*/
        });
    </script>
    <div>
        <section>
            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background: url(/uploads/Vidyatech/Careers/careers.jpg) no-repeat 100% 10" +
"0%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"padding:30px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 173 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
               Write(RenderSection("CMSSectionBanner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </section>\r\n    </div>\r\n\r\n " +
"   <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin:10px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 183 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
               Write(RenderSection("CMSSectionLink", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n            </div>\r\n        </section>\r\n    </div>\r\n " +
"   <div");

WriteLiteral(" class=\"clearfix anchor\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding-left:20px;padding-right:20px;margin-top:20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 195 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                   Write(RenderSection("CMSSectionContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                </div>\r\n            </div>\r\n     " +
"   </section>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding-left:20px;padding-right:20px;margin-top:20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 207 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                   Write(RenderSection("CMSSectionContent2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                </div>\r\n            </div>\r\n     " +
"   </section>\r\n    </div>\r\n\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" id=\"tcareers\"");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding-left:20px;padding-right:20px;;margin-top:20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n\r\n\r\n");

WriteLiteral("                            ");

            
            #line 223 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionOpening1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n                        </div>\r\n\r\n\r\n                    </div>\r\n\r\n         " +
"       </div>\r\n\r\n\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div>" +
"\r\n        <section>\r\n            <div");

WriteLiteral(" id=\"showhide\"");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding-left:20px;padding-right:20px;;margin-top:20px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 243 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionOpening2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <br>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n                        </div" +
">\r\n                    </div>\r\n                </div>\r\n            </div>\r\n\r\n   " +
"     </section>\r\n    </div>\r\n\r\n\r\n\r\n\r\n\r\n    <br><br><br>\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background: url(/uploads/Vidyatech/Careers/img_demo.png); background-size" +
": cover; padding-top: 70px; padding-bottom: 20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    \r\n");

WriteLiteral("                    ");

            
            #line 273 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
               Write(RenderSection("CMSSectionContactBanner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n\r\n\r\n            </div>\r\n        </section>\r\n    </div" +
">\r\n\r\n\r\n\r\n\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div> \t\r\n    <!---->\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color:#2e3133;padding:45px 0\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 295 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 298 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 301 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 304 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSectionLogo", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns end\"");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n                          \r\n                                    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(" style=\"overflow-x:hidden;\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" id=\"patner\"");

WriteLiteral(" style=\"background: white;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 310 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
                                       Write(RenderSection("CMSSectionFooterSectionSlider", false));

            
            #line default
            #line hidden
WriteLiteral(@"
                                           
                                        </div>
                                    </div>
                                </div>
                                <!--<div class=""large-12 columns"">
             <div class=""socialmedia"">
                <a href=""https://www.facebook.com/Vidyatech"" target=""_blank""><img src=""images/social/fb.png"" /></a>
                <a href=""https://plus.google.com/114894168344443802562/about"" target=""_blank""><img src=""images/social/gplus.png"" /></a>
                <a href=""http://www.linkedin.com/company/vidyatech"" target=""_blank""><img src=""images/social/in.png"" /></a>
                <a href=""https://twitter.com/Quiz_Magic"" target=""_blank""><img src=""images/social/twitter.png"" /></a>
                <a href=""http://www.youtube.com/user/proofguru"" target=""_blank""><img src=""images/social/youtube.png"" /></a>
             </div>
             </div>-->

                            </div>
                        </div>
            </div>
        </section>
    </div>
    <footer");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color: #222526;border-color: #333637;color: #646464;min-height" +
": 50px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"margin: 18px auto 0; margin-top:30px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 333 "..\..\Views\Shared\Layouts\VidyatechCareersPage.cshtml"
           Write(RenderSection("CMSSectionPreFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </footer>\r\n\r\n\r\n\r\n    <!------>\r\n    <sc" +
"ript");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.easing.1.3.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.mobile.customized.min.js\"");

WriteLiteral("></script>\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.sticky.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/modernizr.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.nav.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.scrollTo.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.flexisel.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/slick.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/modernizr.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/respond.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.carouFredSel-6.0.4-packed.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.placeholder.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.h5validate.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/custom.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/camera.js\"");

WriteLiteral("></script>\r\n\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-11012032-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>






    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        setTimeout(function () { jQuery(document).ready(function ($) { $('body').css({ 'visibility': 'visible' }); }); }, 400);
    </script>
    <script>
        jQuery(document).ready(function () {
            var hashtag = /#\S+/
            jQuery('.menu li a').click(function () {
                var match = jQuery(this).attr('href').match(hashtag);
                ga('send', 'pageview', '/' + match[0]);
            })
        });
    </script>

</body>

</html>
");

        }
    }
}
#pragma warning restore 1591
