#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
    using BetterCms.Module.Installation;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/VidyatechServicesPage.cshtml")]
    public partial class _Views_Shared_Layouts_VidyatechServicesPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_VidyatechServicesPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("<!doctype html>\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" style=\"overflow-x:hidden\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Cache-Control\"");

WriteLiteral(" content=\"no-store\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <title>Application Development | Vidyatech Solution Pvt. Ltd.</title>\r\n " +
"   <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"images/Vidya.ico\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(@" content=""Vidyatech provides custom software services for building, migrating and maintaining Internet / Cloud based systems. We specialize in content technologies and have extensive experience in Collaborative Content Development, Content Analytics, Social Media, Mobile Devices  and Content Security.""");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(@" content=""Custom Application Development, Mobile Application Development, SharePoint Application Development, Content Migration, Cloud Computing, Web Application Development, Content Localization, Software Testing, Business Intelligence, Content Management, CMS Customization, Legacy System Migration, Content Analytics, Social Media, Content Security""");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/new.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/coolC.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/flexisel.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/home.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/social.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/slick.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/camara.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"https://www.google.com/jsapi\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"http://www.google.com/uds/solutions/dynamicfeed/gfdynamicfeedcontrol.js\"");

WriteLiteral("\r\n            type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery-1.7.1.min.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/custom.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/camara.js \"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        //document.write(\'<style type=\"text/css\">body {visibility:hidden;}</st" +
"yle>\');\r\n\r\n    </script>\r\n\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://www.google.com/jsapi?key=[apikey]\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.j" +
"s\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/additional-methods.js" +
"\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        //document.write('<style type=""text/css"">body {visibility:hidden;}</style>');

    </script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-54469785-1', 'auto');
        ga('require', 'linkid', 'linkid.js');
        ga('send', 'pageview', location.pathname + location.search + location.hash);

        setTimeout(""ga('send','event','Profitable Engagement','time on page more than 1 minute')"", 60000);



    </script>












</head>
<body>
    <!----->
    <!--
      <div id=""preloader"">
          <div id=""status""></div>
      </div>

      <div class=""clearfix""></div>
      <!--NEW MENU CODE -->
    <div>
        <section>

            <nav");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 97 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
           Write(RenderSection("CMSSectionHeader", false));

            
            #line default
            #line hidden
WriteLiteral(@"
            </nav>
        </section>
    </div>
    <!---- NEW MENU CODE ENDS -->
    <script>
        var menuOpen = (function () {
            jQuery(""#show"").click(function () {
                jQuery(""#menuOption"").slideToggle(""fast"");
                jQuery(""#menuOption"").css(""overflow-y"", ""scroll"");
            });
            /*
            jQuery('#serviceli').hover(function () {
                jQuery('#submenu').slideDown(""slow"");

                });*/
        });
    </script>
    <div>
        <section>
            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background: url(/uploads/Vidyatech/ServicePage/handimage.jpg); background" +
"-size: cover; padding: 45px 0; color: #fff;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"servicebar\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 120 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                   Write(RenderSection("CMSSectionServiceBanner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        \r\n                \r\n                    </div>\r\n\r\n     " +
"           </div>\r\n            </div>\r\n        </section>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"margin:10px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                    ");

            
            #line 135 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
               Write(RenderSection("CMSSectionLink", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div></div>\r\n        </section>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix anchor\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:0;margin-top:20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12\"");

WriteLiteral(" style=\"margin:0 10px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 145 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                   Write(RenderSection("CMSSectionContent1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                     </div>\r\n                </div>\r\n            </div>\r\n      " +
"    \r\n        </section>\r\n    </div>\r\n    <div>\r\n        <section>\r\n            " +
"<div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"padding:0;margin-top:20px;background-color:#ececec;padding-bottom:40px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 157 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                   Write(RenderSection("CMSSectionServices", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\t\r\n      " +
"     \r\n        </section>\r\n    </div>\r\n\r\n\r\n    <!---->\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background: url(/uploads/Vidyatech/Careers/img_demo.png); background-size" +
": cover; padding-top: 70px; padding-bottom: 20px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                    ");

            
            #line 174 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
               Write(RenderSection("CMSSectionContactBanner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                </div>\r\n\r\n\r\n            </div>\r\n        </section>\r\n    </div" +
">\r\n\r\n\r\n\r\n\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    <!---->\r\n    <div>\r\n        <section>\r\n            <div");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color:#2e3133;padding:45px 0\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"large-12 columns\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 196 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 199 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 202 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSection3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 205 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                       Write(RenderSection("CMSSectionFooterSectionLogo", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"large-3 medium-6 columns end\"");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n\r\n                         \r\n");

WriteLiteral("                                    ");

            
            #line 210 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
                               Write(RenderSection("CMSSectionFooterSectionSlider", false));

            
            #line default
            #line hidden
WriteLiteral(@"
                                </div>
                                <!--<div class=""large-12 columns"">
             <div class=""socialmedia"">
                <a href=""https://www.facebook.com/Vidyatech"" target=""_blank""><img src=""images/social/fb.png"" /></a>
                <a href=""https://plus.google.com/114894168344443802562/about"" target=""_blank""><img src=""images/social/gplus.png"" /></a>
                <a href=""http://www.linkedin.com/company/vidyatech"" target=""_blank""><img src=""images/social/in.png"" /></a>
                <a href=""https://twitter.com/Quiz_Magic"" target=""_blank""><img src=""images/social/twitter.png"" /></a>
                <a href=""http://www.youtube.com/user/proofguru"" target=""_blank""><img src=""images/social/youtube.png"" /></a>
             </div>
             </div>-->

                            </div>
                        </div>
            </div>
        </section>
    </div>
    <footer");

WriteLiteral(" class=\"section\"");

WriteLiteral(" style=\"background-color: #222526;border-color: #333637;color: #646464;min-height" +
": 50px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"margin: 18px auto 0; margin-top:30px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 230 "..\..\Views\Shared\Layouts\VidyatechServicesPage.cshtml"
           Write(RenderSection("CMSSectionPreFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </footer>\r\n    <!---->\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.easing.1.3.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.mobile.customized.min.js\"");

WriteLiteral("></script>\r\n\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.sticky.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/modernizr.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.nav.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.scrollTo.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.flexisel.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/slick.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/modernizr.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/respond.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.carouFredSel-6.0.4-packed.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.placeholder.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/jquery.h5validate.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/custom.js\"");

WriteLiteral("></script>\r\n  \r\n\r\n   \r\n    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-11012032-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>





    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        setTimeout(function () { jQuery(document).ready(function ($) { $('body').css({ 'visibility': 'visible' }); }); }, 400);
    </script>
    <script>
        jQuery(document).ready(function () {
            var hashtag = /#\S+/
            jQuery('.menu li a').click(function () {
                var match = jQuery(this).attr('href').match(hashtag);
                ga('send', 'pageview', '/' + match[0]);
            })
        });
    </script>
</body>
</html>


<!------>
");

        }
    }
}
#pragma warning restore 1591
