#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/Vinod_MainTemplate.cshtml")]
    public partial class _Views_Shared_Layouts_Vinod_MainTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_Vinod_MainTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta charset=\"utf-" +
"8\" />\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>-->\r\n\r\n");

            
            #line 12 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/jetmenu.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/hover_pack.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jetmenu.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/application.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.simple-text-rotator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.unveilEffects.js\"");

WriteLiteral("></script>\r\n<script>\r\n    function openCity(evt, cityName) {\r\n        // Declare " +
"all variables\r\n        var i, tabcontent, tablinks;\r\n\r\n        // Get all elemen" +
"ts with class=\"tabcontent\" and hide them\r\n        tabcontent = document.getEleme" +
"ntsByClassName(\"tabcontent\");\r\n        for (i = 0; i < tabcontent.length; i++) {" +
"\r\n            tabcontent[i].style.display = \"none\";\r\n        }\r\n\r\n        // Get" +
" all elements with class=\"tablinks\" and remove the class \"active\"\r\n        tabli" +
"nks = document.getElementsByClassName(\"tablinks\");\r\n        for (i = 0; i < tabl" +
"inks.length; i++) {\r\n            tablinks[i].className = tablinks[i].className.r" +
"eplace(\" active\", \"\");\r\n        }\r\n\r\n        // Show the current tab, and add an" +
" \"active\" class to the button that opened the tab\r\n        document.getElementBy" +
"Id(cityName).style.display = \"block\";\r\n        evt.currentTarget.className += \" " +
"active\";\r\n    }\r\n</script>\r\n\r\n<style>\r\n    div.tab {\r\n    /*overflow: hidden;\r\n " +
"   border: 1px solid #ccc;*/\r\n    background-color: white;\r\n}\r\n\r\n/* Style the bu" +
"ttons inside the tab */\r\ndiv.tab button {\r\n    /*background-color: inherit;*/\r\n " +
"   float: left;\r\n    border: none;\r\n    outline: none;\r\n    cursor: pointer;\r\n  " +
"  padding: 25px 16px;\r\n    transition: 0.3s;\r\n    font-size:14px;\r\n    font-fami" +
"ly:Oswald-Bold;\r\n    color:white;\r\n    width: 32%;\r\n    background-image: linear" +
"-gradient(to bottom, #858585 0%, #858585 100%);\r\n    margin-right:2%;\r\n}\r\n\r\n/* C" +
"hange background color of buttons on hover */\r\ndiv.tab button:hover {\r\n    backg" +
"round-color: #ddd;\r\n}\r\n\r\n/* Create an active/current tablink class */\r\ndiv.tab b" +
"utton.active {\r\n    //background-image: linear-gradient(to bottom, #858585 0%, #" +
"858585 100%);\r\n    background-image: linear-gradient(to bottom, #00a4db 0%, #007" +
"acc 100%);\r\n}\r\n\r\n/* Style the tab content */\r\n.tabcontent {\r\n    display: none;\r" +
"\n    /*padding: 6px 12px;\r\n    border: 1px solid #ccc;\r\n    border-top: none;*/\r" +
"\n}\r\n\r\n.grey-text{\r\n    font-family:OpenSans-Regular;\r\n    font-size:14px;\r\n    c" +
"olor:#696969;\r\n}\r\n    .table-titles {\r\n    padding: 18px;\r\n    background: #ecec" +
"ec;\r\n    \r\n    font-family:OpenSans-Bold;\r\n    font-size:14px;\r\n    color:black;" +
"\r\n}\r\n.col-lg-2.col-md-2.table-titles,.col-lg-10.col-md-10.table-titles {\r\n    pa" +
"dding-left:18px!important;\r\n}\r\n\r\n.tabcontent-row{\r\n    padding-top: 18px;\r\n    p" +
"adding-bottom: 18px;\r\n    padding-left: 18px;\r\n    border-bottom: 1px solid #a4a" +
"4a4;\r\n    font-family:OpenSans-Regular;\r\n    font-size:14px;\r\n    color:black;\r\n" +
"}\r\n.tabcontent-para p{\r\n    padding-bottom:15px;\r\n}\r\n.tabcontent-para p:last-of-" +
"type{\r\n    padding-bottom:0px;\r\n}\r\n.tabcontent-para {\r\n    margin-bottom:35px;\r\n" +
"}\r\n.tabcontent-para p.content-text.sub-heading {\r\n    font-family:Oswald-Bold!im" +
"portant;\r\n    padding-bottom:0px!important;\r\n    font-size:16px!important;\r\n}\r\n#" +
"Researchexperience .tabcontent-row .col-lg-10.col-md-10 p{\r\n    padding-bottom:3" +
"px!important;\r\n}\r\n</style>\r\n<div>\r\n    <div");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            \r\n\r\n\r\n");

WriteLiteral("            ");

            
            #line 157 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
       Write(RenderSection("CMSHeader1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <header");

WriteLiteral(" class=\"header-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-header clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" class=\"affix-top\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-3 col-md-3 col-sm-12 title-area pull-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(" id=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 166 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
                       Write(RenderSection("CMSHeader2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div><!-- site title -->\r\n                    </div><!" +
"-- title area -->\r\n                    \r\n                    <div");

WriteLiteral(" class=\"col-lg-9 col-md-9 col-sm-12\"");

WriteLiteral(" style=\"margin-top:30px\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 171 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
                   Write(RenderSection("CMSHeader3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </header>\r\n</div>\r\n\r\n\r\n\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-bottom:50px;padding-top:0px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Overview\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 191 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
               Write(RenderSection("CMSTab1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Researchexperience\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 197 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
               Write(RenderSection("CMSTab2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"tabcontent\"");

WriteLiteral(" id=\"Publications\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 241 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
               Write(RenderSection("CMSTab3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n\r\n\r\n\r\n\r\n\r\n            </div><!-- end container -->\r\n   " +
"     </section>\r\n    </div>\r\n\r\n</div>\r\n\r\n\r\n\r\n\r\n<footer>\r\n    <div>\r\n        <div" +
"");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            \r\n");

WriteLiteral("            ");

            
            #line 261 "..\..\Views\Shared\Layouts\Vinod_MainTemplate.cshtml"
       Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</footer>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
