#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Layouts/Vinod_about.cshtml")]
    public partial class _Views_Shared_Layouts_Vinod_about_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Layouts_Vinod_about_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title></title>\r\n\t<meta charset=\"utf-8\" " +
"/>\r\n</head>\r\n<body>\r\n\r\n</body>\r\n</html>-->\r\n    \r\n");

            
            #line 12 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
  
    Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

});

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/jetmenu.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/hover_pack.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jetmenu.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/application.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.simple-text-rotator.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.unveilEffects.js\"");

WriteLiteral("></script>\r\n\r\n<div>\r\n    <div");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("            ");

            
            #line 74 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
       Write(RenderSection("CMSHeader1", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <header");

WriteLiteral(" class=\"header-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-header clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"nav\"");

WriteLiteral(" class=\"affix-top\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-3 col-md-3 col-sm-12 title-area pull-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(" id=\"title\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 86 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
                       Write(RenderSection("CMSHeader2", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div><!-- site title -->\r\n                    </div><!" +
"-- title area -->\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-lg-9 col-md-9 col-sm-12\"");

WriteLiteral(" style=\"margin-top:30px\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 105 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
                   Write(RenderSection("CMSHeader3", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </header>\r\n</div>\r\n\r\n<div>\r\n    ");

WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" id=\"\"");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 119 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
       Write(RenderSection("Banner", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-bottom:24px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("               ");

            
            #line 127 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
          Write(RenderSection("CMSAboutdiseases", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</d" +
"iv>\r\n<div>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitebg\"");

WriteLiteral(" style=\"padding-bottom:50px;padding-top:0px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n\r\n\r\n\r\n");

WriteLiteral("               ");

            
            #line 147 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
          Write(RenderSection("CMSAboutdiseases_accordion", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div><!-- end container -->\r\n        </section>\r\n    </div>\r\n\r\n</d" +
"iv>\r\n\r\n\r\n\r\n<footer>\r\n    <div>\r\n        <div");

WriteLiteral(" id=\"footer\"");

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 170 "..\..\Views\Shared\Layouts\Vinod_about.cshtml"
       Write(RenderSection("CMSFooter", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</footer>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
