#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Widgets\01.cshtml"
    using BetterCms.Module.Api;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Widgets\01.cshtml"
    using BetterCms.Module.Api.Operations.Pages.Pages.Search;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/01.cshtml")]
    public partial class _Views_Widgets_01_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Widgets_01_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 30 "..\..\Views\Widgets\01.cshtml"
  
    using (var container = ApiFactory.Create())
    {
        var results = container.Pages.Pages.Search(new SearchPagesRequest { SearchString = "test" });


            
            #line default
            #line hidden
WriteLiteral("        <div>Showing ");

            
            #line 35 "..\..\Views\Widgets\01.cshtml"
                Write(results.Data.Items.Count);

            
            #line default
            #line hidden
WriteLiteral(" results of ");

            
            #line 35 "..\..\Views\Widgets\01.cshtml"
                                                     Write(results.Data.TotalCount);

            
            #line default
            #line hidden
WriteLiteral("</div>\n");

            
            #line 36 "..\..\Views\Widgets\01.cshtml"

        foreach (var item in results.Data.Items)
        {
            var cssClass = item.IsDenied ? "bcms-search-result" : "bcms-search-result bcms-denied-search-result";


            
            #line default
            #line hidden
WriteLiteral("            <article");

WriteAttribute("class", Tuple.Create(" class=\"", 1803), Tuple.Create("\"", 1820)
            
            #line 41 "..\..\Views\Widgets\01.cshtml"
, Tuple.Create(Tuple.Create("", 1811), Tuple.Create<System.Object, System.Int32>(cssClass
            
            #line default
            #line hidden
, 1811), false)
);

WriteLiteral(">\n                <h3>");

            
            #line 42 "..\..\Views\Widgets\01.cshtml"
               Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1878), Tuple.Create("\"", 1904)
            
            #line 43 "..\..\Views\Widgets\01.cshtml"
, Tuple.Create(Tuple.Create("", 1885), Tuple.Create<System.Object, System.Int32>(item.Link ?? "#"
            
            #line default
            #line hidden
, 1885), false)
);

WriteLiteral(">");

            
            #line 43 "..\..\Views\Widgets\01.cshtml"
                                         Write(item.FormattedUrl);

            
            #line default
            #line hidden
WriteLiteral("</a>\n                <p>");

            
            #line 44 "..\..\Views\Widgets\01.cshtml"
              Write(item.Snippet);

            
            #line default
            #line hidden
WriteLiteral("</p>\n            </article>\n");

            
            #line 46 "..\..\Views\Widgets\01.cshtml"
        }
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
