#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/03.cshtml")]
    public partial class _Views_Widgets_03_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Widgets_03_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n<span>\n    Widget (02).\n    Current time ");

            
            #line 30 "..\..\Views\Widgets\03.cshtml"
            Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("\n</span>\n<br/>\n<span>\nNo extra logic here.\n</span>\n\n<span>\nWidget (03).\nCurrent t" +
"ime ");

            
            #line 39 "..\..\Views\Widgets\03.cshtml"
        Write(DateTime.Now);

            
            #line default
            #line hidden
WriteLiteral("\n</span>\n<br/>\n<span>\nHtml helper:\n</span>\n<br/>\n\n<span>\n");

WriteLiteral("    ");

            
            #line 48 "..\..\Views\Widgets\03.cshtml"
Write(Html.RadioButton("test", "test1"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Views\Widgets\03.cshtml"
Write(Html.RadioButton("test", "test2"));

            
            #line default
            #line hidden
WriteLiteral("\n</span>\n\n");

            
            #line 52 "..\..\Views\Widgets\03.cshtml"
Write(Html.Partial("Partial/TestOptionValues"));

            
            #line default
            #line hidden
WriteLiteral("\n\n");

        }
    }
}
#pragma warning restore 1591
