#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Widgets\MenuWidget.cshtml"
    using BetterCms.Sandbox.Mvc4.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MenuWidget.cshtml")]
    public partial class _Views_Widgets_MenuWidget_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Widgets_MenuWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 29 "..\..\Views\Widgets\MenuWidget.cshtml"
  
//    var languageCode = OptionsHelper.GetValue(Model.Options, "languageCode");
//    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = languageCode });


            
            #line default
            #line hidden
WriteLiteral("    <strong>Sitemap API test:</strong>\n");

WriteLiteral("    <p>Lithuanian:</p>\n");

            
            #line 35 "..\..\Views\Widgets\MenuWidget.cshtml"
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "lt" });

            
            #line default
            #line hidden
WriteLiteral("    <p>English:</p>\n");

            
            #line 37 "..\..\Views\Widgets\MenuWidget.cshtml"
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "en" });

            
            #line default
            #line hidden
WriteLiteral("    <p>Default:</p>\n");

            
            #line 39 "..\..\Views\Widgets\MenuWidget.cshtml"
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty, languageCode = "default" });
    

            
            #line default
            #line hidden
WriteLiteral("    <p>As inserted to the sitemap:</p>\n");

            
            #line 42 "..\..\Views\Widgets\MenuWidget.cshtml"
    Html.RenderAction("SitemapMenu", "Sandbox", new { area = string.Empty });

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
