#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/TestPostAndGet.cshtml")]
    public partial class _Views_Widgets_TestPostAndGet_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Sandbox.Mvc4.Models.TestPostAndGetViewModel>
    {
        public _Views_Widgets_TestPostAndGet_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("<h1>Model title value: ");

            
            #line 30 "..\..\Views\Widgets\TestPostAndGet.cshtml"
                  Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n<form");

WriteLiteral(" method=\"POST\"");

WriteLiteral(">\n    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1456), Tuple.Create("\"", 1476)
            
            #line 33 "..\..\Views\Widgets\TestPostAndGet.cshtml"
, Tuple.Create(Tuple.Create("", 1464), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 1464), false)
);

WriteLiteral(" />\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"POST\"");

WriteLiteral(" />\n</form>\n\n<form");

WriteLiteral(" method=\"GET\"");

WriteLiteral(">\n    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1586), Tuple.Create("\"", 1606)
            
            #line 38 "..\..\Views\Widgets\TestPostAndGet.cshtml"
, Tuple.Create(Tuple.Create("", 1594), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 1594), false)
);

WriteLiteral(" />\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"GET\"");

WriteLiteral(" />\n</form>");

        }
    }
}
#pragma warning restore 1591
