#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Partial/TestOptionValues.cshtml")]
    public partial class _Views_Shared_Partial_TestOptionValues_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Partial_TestOptionValues_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n\n<br /><br />\n<b>Option Key1 Value</b><span>: ");

            
            #line 30 "..\..\Views\Shared\Partial\TestOptionValues.cshtml"
                           Write(Html.ViewBag.Key1);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\n<b>Option Key2 Value</b><span>: ");

            
            #line 31 "..\..\Views\Shared\Partial\TestOptionValues.cshtml"
                           Write(Html.ViewBag.Key2);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\n<b>Option Key3 Value</b><span>: ");

            
            #line 32 "..\..\Views\Shared\Partial\TestOptionValues.cshtml"
                           Write(Html.ViewBag.Key3);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\n<b>Option Key4 Value</b><span>: ");

            
            #line 33 "..\..\Views\Shared\Partial\TestOptionValues.cshtml"
                           Write(Html.ViewBag.Key4);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />\n<b>Option Key5 Value</b><span>: ");

            
            #line 34 "..\..\Views\Shared\Partial\TestOptionValues.cshtml"
                           Write(Html.ViewBag.Key5);

            
            #line default
            #line hidden
WriteLiteral("</span> <br />");

        }
    }
}
#pragma warning restore 1591
