#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 34 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Root.Content.Resources;
    
    #line default
    #line hidden
    
    #line 35 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 36 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Users.Content.Resources;
    
    #line default
    #line hidden
    
    #line 37 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Users.Controllers;
    
    #line default
    #line hidden
    
    #line 30 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Users.Services;
    
    #line default
    #line hidden
    
    #line 31 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Users.ViewModels;
    
    #line default
    #line hidden
    
    #line 38 "..\..\Views\Authentication\Signup.cshtml"
    using BetterCms.Module.Users.ViewModels.User;
    
    #line default
    #line hidden
    
    #line 39 "..\..\Views\Authentication\Signup.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Authentication/Signup.cshtml")]
    public partial class _Views_Authentication_Signup_cshtml : System.Web.Mvc.WebViewPage<EditUserViewModel>
    {
        public _Views_Authentication_Signup_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 43 "..\..\Views\Authentication\Signup.cshtml"
  
    Layout = "~/Areas/bcms-users/Views/Shared/PublicActionLayout.cshtml";
    ViewBag.Title = "Signup";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1938), Tuple.Create("\"", 1973)
, Tuple.Create(Tuple.Create("", 1944), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-3.1.1.min.js")
, 1944), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1993), Tuple.Create("\"", 2031)
, Tuple.Create(Tuple.Create("", 1999), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.validate.min.js")
, 1999), false)
);

WriteLiteral("></script>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 52 "..\..\Views\Authentication\Signup.cshtml"
   Write(ViewBag.result);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 53 "..\..\Views\Authentication\Signup.cshtml"
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Authentication\Signup.cshtml"
     if (!string.IsNullOrEmpty( ViewBag.result))
    { 

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        setTimeout(function () {\r\n            window.location.href " +
"= \'/login\';\r\n        }, 3000);\r\n    </script>\r\n");

            
            #line 60 "..\..\Views\Authentication\Signup.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"divBasicLogin\"");

WriteLiteral(">\r\n");

            
            #line 62 "..\..\Views\Authentication\Signup.cshtml"
        
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Authentication\Signup.cshtml"
         using (Html.BeginForm())
        {
            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Authentication\Signup.cshtml"
       Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Authentication\Signup.cshtml"
                                      
            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Authentication\Signup.cshtml"
       Write(Html.HiddenFor(m => m.Version));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Authentication\Signup.cshtml"
                                           


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-form-block-holder\"");

WriteLiteral(">\r\n                <div>\r\n                    <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 70 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_FirstName_Title);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 72 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.FirstName, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 73 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.BcmsValidationMessageFor(m => m.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_LastName);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 80 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.LastName, new { @class = "bcms-field-text"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 81 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.BcmsValidationMessageFor(m => m.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_UserName_Title);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        \r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 89 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.UserName, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 90 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.BcmsValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 95 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_Email_Title);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 97 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.Email, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 98 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 103 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_Password_Title);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 105 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.Password, new { @class = "bcms-field-text", @type = "password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 106 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.BcmsValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 111 "..\..\Views\Authentication\Signup.cshtml"
                                                    Write(UsersGlobalization.EditUser_RetypePassword_Title);

            
            #line default
            #line hidden
WriteLiteral(" <span>*</span></div>\r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 113 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.TextBoxFor(m => m.RetypedPassword, new { @class = "bcms-field-text", @type = "password" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 114 "..\..\Views\Authentication\Signup.cshtml"
                       Write(Html.BcmsValidationMessageFor(m => m.RetypedPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"bcms-input-list-holder\"");

WriteLiteral(">\r\n                        \r\n                        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" class=\"bcms-btn-tertiary\"");

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" class=\"bcms-btn-secondary\"");

WriteLiteral(" onclick=\"javascript:window.location.href=\'/login\'\"");

WriteLiteral(" />\r\n                            \r\n                        </div>\r\n              " +
"      </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 127 "..\..\Views\Authentication\Signup.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"    </div>
</div>
    
<style>
    .bcms-input-list-holder {
    margin-top:0px;
    }
    .error {
        color: #dc4250;
        /*font-size: 11px;*/
        /*margin-left: 5px;*/
    }
    .field-validation-error {
        font-size: 13px;
        margin-left: 0px;
    }
    .bcms-content-titles span {
    color:red;
    }
</style>
<script>
    
    $.validator.addMethod('validateusername', function (value, element) {
        var expr = /^[^\\\/\""\[\]\:\;\|\=\,\+\*\?\<\>\%]+$/;
        return expr.test(value);
    }, 'The field must not contain any of the following characters: "" / [ ] : ; | = , + * ? < > % or backslash');

    $.validator.addMethod('validateemail', function (value, element) {
        var expr = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+");

WriteLiteral("@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)+$/;\r\n        return expr.test(value);\r\n    }, \'" +
"Email format is not valid.\');\r\n\r\n    $(\"form\").validate({\r\n        rules: {\r\n   " +
"         FirstName: {\r\n                required: true,\r\n                rangelen" +
"gth: [1, 200]\r\n            },\r\n            LastName: {\r\n                required" +
": true,\r\n                rangelength: [1, 200]\r\n            },\r\n            User" +
"Name: {\r\n                required: true,\r\n                rangelength: [1, 401]," +
"\r\n                validateusername:true\r\n            },\r\n            Email: {\r\n " +
"               required: true,\r\n                rangelength: [1, 400],\r\n        " +
"        validateemail: true\r\n            },\r\n            Password: {\r\n          " +
"      rangelength: [4, 255],\r\n                required: true\r\n            },\r\n  " +
"          RetypedPassword: {\r\n                equalTo: \"#Password\"\r\n            " +
"},\r\n        },\r\n\r\n        messages: {\r\n            FirstName: {\r\n               " +
" required: \"First name is required.\",\r\n                rangelength: \"First name " +
"should not be longer than 200 characters.\"\r\n            },\r\n            LastName" +
": {\r\n                required: \"Last name is required.\",\r\n                rangel" +
"ength: \"Last name should not be longer than 200 characters.\"\r\n            },\r\n  " +
"          UserName: {\r\n                required: \"Username is required.\",\r\n     " +
"           rangelength: \"User name should not be longer than 401 character.\"\r\n  " +
"          },\r\n            Email: {\r\n                required: \"Email is required" +
".\",\r\n                rangelength: \"Email should not be longer than 400 character" +
"s.\"\r\n            },\r\n            Password: {\r\n                required: \"Passwor" +
"d is required.\",\r\n                rangelength: \"Password should not be shorter t" +
"han 4 characters and not be longer than 255 characters and cannot start or end w" +
"ith empty space.\"\r\n            },\r\n            RetypedPassword: {\r\n             " +
"   equalTo: \"Password and retyped password should match.\"\r\n            }\r\n      " +
"  },\r\n        submitHandler: function (form) {\r\n            $(form).find(\"input[" +
"type=\'submit\']\").attr(\'disabled\', true);\r\n            $(form).find(\"input[type=\'" +
"button\']\").attr(\'disabled\', true);\r\n            form.submit();\r\n        },\r\n    " +
"    invalidHandler: function (event, validator) {\r\n        }\r\n    });\r\n</script>" +
"");

        }
    }
}
#pragma warning restore 1591
