#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Upload/Upload.cshtml")]
    public partial class _Views_Upload_Upload_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Sandbox.Mvc4.Models.TestUploadViewModel>
    {
        public _Views_Upload_Upload_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("<h1>Sandbox Upload Tester</h1>\n\n");

            
            #line 32 "..\..\Views\Upload\Upload.cshtml"
 if (Model != null && Model.Result != null)
{
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Upload\Upload.cshtml"
Write(Html.Raw(Model.Result));

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Upload\Upload.cshtml"
                           
}

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 37 "..\..\Views\Upload\Upload.cshtml"
 using (Html.BeginForm("Upload", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <span>Select type of uploading file:</span>\n");

WriteLiteral("    <p>\n        <select");

WriteLiteral(" name=\"type\"");

WriteLiteral(">\n            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Image</option>\n            <option");

WriteLiteral(" value=\"file\"");

            
            #line 43 "..\..\Views\Upload\Upload.cshtml"
                            Write(Model != null && Model.Type == "file" ? " selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">File</option>\n        </select>\n    </p>\n");

            
            #line 46 "..\..\Views\Upload\Upload.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <span>Select type of upload method (determines, if response should wait while" +
" file is being processed to the storage):</span>\n");

WriteLiteral("    <p>\n        <select");

WriteLiteral(" name=\"method\"");

WriteLiteral(">\n            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Asynchronous (do not wait)</option>\n            <option");

WriteLiteral(" value=\"sync\"");

WriteLiteral(" ");

            
            #line 51 "..\..\Views\Upload\Upload.cshtml"
                             Write(Model != null && Model.Method == "sync" ? " selected" : string.Empty);

            
            #line default
            #line hidden
WriteLiteral(">Synchronous (wait)</option>\n        </select>\n    </p>\n");

WriteLiteral("    <p>\n        <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"file\"");

WriteLiteral(" />\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"upload\"");

WriteLiteral(" />\n    </p>\n");

            
            #line 58 "..\..\Views\Upload\Upload.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\n");

        }
    }
}
#pragma warning restore 1591
