#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Sandbox/Login.cshtml")]
    public partial class _Views_Sandbox_Login_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Sandbox.Mvc4.Models.LoginViewModel>
    {
        public _Views_Sandbox_Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 30 "..\..\Views\Sandbox\Login.cshtml"
  
    var isAuthenticated = Model.Identity != null && Model.Identity.IsAuthenticated;

            
            #line default
            #line hidden
WriteLiteral("\n\n<div>\n");

            
            #line 35 "..\..\Views\Sandbox\Login.cshtml"
    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Sandbox\Login.cshtml"
     using (Html.BeginForm(isAuthenticated ? "Logout" : "Login", "Sandbox")) {
        if (!isAuthenticated)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.LabelFor(m => m.UserName, "User name:"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.TextBoxFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");

            
            #line 42 "..\..\Views\Sandbox\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div>\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.LabelFor(m => m.Password, "Password:"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 45 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.PasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n");

            
            #line 47 "..\..\Views\Sandbox\Login.cshtml"

            if (ViewBag.ShowFieldRememberMe != null)
            {
                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Sandbox\Login.cshtml"
                                                    
                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Sandbox\Login.cshtml"
           Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Sandbox\Login.cshtml"
                                                 
            }
            

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Login\"");

WriteLiteral(" />\n");

            
            #line 55 "..\..\Views\Sandbox\Login.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <p>");

            
            #line 58 "..\..\Views\Sandbox\Login.cshtml"
          Write(Model.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("</p>\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Logout\"");

WriteLiteral(" />\n");

            
            #line 60 "..\..\Views\Sandbox\Login.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
