#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SitemapMenu/Index.cshtml")]
    public partial class _Views_SitemapMenu_Index_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Sandbox.Mvc4.Models.SitemapMenuViewModel>
    {
        public _Views_SitemapMenu_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

WriteLiteral("<h2>Obsolete <i>");

            
            #line 30 "..\..\Views\SitemapMenu\Index.cshtml"
            Write(Model.LanguageCode ?? "default Language");

            
            #line default
            #line hidden
WriteLiteral("</i> items:</h2>\n");

            
            #line 31 "..\..\Views\SitemapMenu\Index.cshtml"
 if (Model != null && Model.ObsoleteMenuItems != null)
{
    foreach (var item in Model.ObsoleteMenuItems)
    {
         
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\SitemapMenu\Index.cshtml"
    Write(item.Caption);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1549), Tuple.Create("\"", 1565)
            
            #line 35 "..\..\Views\SitemapMenu\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1556), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 1556), false)
);

WriteLiteral("><span>");

            
            #line 35 "..\..\Views\SitemapMenu\Index.cshtml"
                                            Write(item.Url);

            
            #line default
            #line hidden
WriteLiteral("</span></a> ");

            
            #line 35 "..\..\Views\SitemapMenu\Index.cshtml"
                                                                      
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\SitemapMenu\Index.cshtml"
                                                                  Write(item.IsPublished ? "(Live)" : "");

            
            #line default
            #line hidden
WriteLiteral("<br/>\n");

            
            #line 36 "..\..\Views\SitemapMenu\Index.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\n<h2>New <i>");

            
            #line 39 "..\..\Views\SitemapMenu\Index.cshtml"
       Write(Model.LanguageCode ?? "default Language");

            
            #line default
            #line hidden
WriteLiteral("</i> items:</h2>\n");

            
            #line 40 "..\..\Views\SitemapMenu\Index.cshtml"
 if (Model != null && Model.MenuItems != null)
{
    foreach (var item in Model.MenuItems)
    {
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\SitemapMenu\Index.cshtml"
   Write(item.Caption);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1836), Tuple.Create("\"", 1852)
            
            #line 44 "..\..\Views\SitemapMenu\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1843), Tuple.Create<System.Object, System.Int32>(item.Url
            
            #line default
            #line hidden
, 1843), false)
);

WriteLiteral("><span>");

            
            #line 44 "..\..\Views\SitemapMenu\Index.cshtml"
                                           Write(item.Url);

            
            #line default
            #line hidden
WriteLiteral("</span></a> ");

            
            #line 44 "..\..\Views\SitemapMenu\Index.cshtml"
                                                                     
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\SitemapMenu\Index.cshtml"
                                                                 Write(item.IsPublished ? "(Live)" : "");

            
            #line default
            #line hidden
WriteLiteral("<br />\n");

            
            #line 45 "..\..\Views\SitemapMenu\Index.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 48 "..\..\Views\SitemapMenu\Index.cshtml"
 if (Model != null && Model.RenderIFrame && Model.LanguageCodes != null)
{
    foreach (var lang in Model.LanguageCodes)
    {

            
            #line default
            #line hidden
WriteLiteral("        <hr />\n");

WriteLiteral("        <iframe");

WriteLiteral(" style=\"padding: 0; overflow: auto; border: 0; width: 1000px; height: 200px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2166), Tuple.Create("\"", 2252)
, Tuple.Create(Tuple.Create("", 2172), Tuple.Create("http://bettercms.sandbox.mvc4.local.net/sandbox/SitemapMenu?languageCode=", 2172), true)
            
            #line 53 "..\..\Views\SitemapMenu\Index.cshtml"
                                                                                            , Tuple.Create(Tuple.Create("", 2245), Tuple.Create<System.Object, System.Int32>(lang
            
            #line default
            #line hidden
, 2245), false)
);

WriteLiteral("></iframe>\n");

            
            #line 54 "..\..\Views\SitemapMenu\Index.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
